### ISSUE TITLE
index.html in the single algorithm folder

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1451] opened 2017-07-10 12:27 UTC
The post-processing output folder for single algorithms does not have an `index.html` file. Is there a reason why it should not?

**Comment by brockho** [comment] 2017-07-11 12:56
To precise a bit: maybe we should simply consider renaming the existing `templateBBOBarticle.html` file to `index.html`.

**Comment by dtusar** [comment] 2017-09-11 10:46
Duplicate of #1513.

**Closed by dtusar** 2017-09-11 10:46 UTC
Labels: Code-Postprocessing, question
