### ISSUE TITLE
Growing Links in HTML output

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1472] opened 2017-08-01 10:43 UTC
When postprocessing the same data again and again within the (i)python shell, the links in the HTML output keep growing until one closes the shell:

![image](https://user-images.githubusercontent.com/13706996/28821542-1bce529e-76b6-11e7-9b6e-9eb281c157e7.png)
vs.
![image](https://user-images.githubusercontent.com/13706996/28821762-0a266e5e-76b7-11e7-81be-13e4d402b759.png)
vs.
![image](https://user-images.githubusercontent.com/13706996/28821470-d63089aa-76b5-11e7-9e10-6410ee05d835.png)
vs.
![image](https://user-images.githubusercontent.com/13706996/28821490-ead18a26-76b5-11e7-9069-8605cedb1e6d.png)

**Comment by islandblue** [comment] 2017-08-08 12:28
Since @dtusar has his hands full with Jenkins at the moment, I've taken the liberty to look into this, since it's quite annoying and seems bite-sized. Hope that's all right.

**Comment by dtusar** [comment] 2017-08-08 13:02
Go ahead.

**Comment by islandblue** [comment] 2017-08-08 13:39
The problem arises when `processInputArgs()` function defined in `pproc.py` is called with the optional `process_background_algorithms` argument set to `True,` which is only done in one place, in the `main()` function in `rungenericmany.py`. The following code is executed:

`genericsettings.foreground_algorithm_list.extend(sortedAlgs)`

There is no code to clear this variable, so it just keeps growing with each subsequent call to `cocopp.main()` where more than one argument is supplied and `rungenericmany.py` gets called.

This raises a lot of red flags for me, because anything that gets assigned values at runtime is a global variable, not a setting, and complications like this is exactly why the use of global variables is frowned upon. Might be worthwhile to consider implementing differently in the overhaul, but I'll focus on a band-aid fix now. Of course, I do not know the original intent, so maybe `genericsettings.foreground_algorithm_list` was _meant to_ grow in some way, but not like this, obviously.

Anyway, running the module from a CLI would never retain this value, so unless we deliberately want different behavior when run from a python shell or inside a script, we should either use direct assignment instead of `extend()` or initialize `genericsettings.foreground_algorithm_list` explicitly before starting to use it. For me, the former is hard to justify, since I'm not quite there yet on why everything is the way it is, but easy to do, whereas the latter is easier to justify, but slightly harder to do, since I am not certain where in the code would be an appropriate place to do the initialization.

You could guide me by sharing your insight or take over from this point if you feel doing is easier than explaining.

**Comment by dtusar** [comment] 2017-08-08 14:30
The idea was that you could also define the foreground algorithms in the `genericsettings` (I don't remember exactly the scenario). 

Regarding the fix for this issue: you should add only new algorithms to the list.

**Comment by nikohansen** [comment] 2017-08-08 15:05
It seems that the main problem is duplicates in the list. One way to address this problem is to use a `set` instead of a `list`. This seems semantically the right data structure here.

It seems reasonable that a call to `main` overwrites the value of `foreground_algorithms`, because the arguments to `main` are to be considered as the foreground algorithms to use. Or am I missing something?

Re settings and global variables: there are settings the user can (in principle) change after startup without breaking any code. True, these can be considered global variables, but yet I would not see the point why the user should not be allowed to change them dynamically just because of that.

I believe `matplotlib.rcParams` is an example of such kind of user interface.

**Comment by islandblue** [comment] 2017-08-08 15:56
The discussion of global variables aside, my understanding of the problem is not one of duplicate entries. I have experiment data for three algorithms in my working folder. For generality, let's call them AlgA, AlgB and AlgC. First I run `cocopp.main("AlgA AlgB")`, which compares these two data and puts the post-processing output into a folder named `AlgA_AlgB`. Then I run `cocopp.main("AlgA AlgC")`, and the behavior I expect is exactly the same as the previous call, except I have AlgC in place of AlgB. That is, I expect a comparison between AlgA and AlgC, with the output going into a folder named `AlgA_AlgC`. However, your proposed solution will result in a comparison between AlgA, AlgB and AlgC, and an output folder named `AlgA_AlgB_AlgC`.

Can you describe to me a meaningful use case where **_retaining_** the value of foreground algorithms between separate calls to `cocopp.main()` serves a purpose? Because if you only intend to make it accessible to the user, allowing him to specify some algorithms to include in the comparison without passing them as arguments (which, in my opinion, allows for very little added freedom; passing arguments is not more difficult than editing a file, maybe even easier when you want to script your post-processing into a batch job), then we could just keep the two things separate and reset the foreground algorithms to its initial state as assigned in genericsettings.py and that would solve this issue, provide consistent behavior between CLI and shell calls and still allow the user to include whatever algorithms he wants in the post-processing.

**Comment by nikohansen** [comment] 2017-08-08 17:51
I wrote: 
> It seems reasonable that a call to main overwrites the value of foreground_algorithms, because the arguments to main are to be considered as the foreground algorithms to use. Or am I missing something?

you wrote: 
> Then I run cocopp.main("AlgA AlgC"), and the behavior I expect is exactly the same as the previous call, except I have AlgC in place of AlgB. That is, I expect a comparison between AlgA and AlgC, with the output going into a folder named AlgA_AlgC. However, your proposed solution will result in a comparison between AlgA, AlgB and AlgC, and an output folder named AlgA_AlgB_AlgC.

I am lost in understanding how my suggestion will lead to the latter outcome (I wrote `foreground_algorithms` when referring to `foreground_algorithm_list`, not sure whether this was the problem).

**Comment by dtusar** [comment] 2017-08-09 07:00
> It seems reasonable that a call to main overwrites the value of foreground_algorithms, because the arguments to main are to be considered as the foreground algorithms to use. 

I agree.

**Comment by islandblue** [comment] 2017-08-09 11:02
I will try a different approach to communicate my point and my concern.

- This line `foreground_algorithm_list = []` in `genericsettings.py` is a parameter definition. It is there for the **_human_** user to change when he wants to alter the behavior of the program.
- Programs do not alter parameters, since they represent the initial preference, the original intention of the user. They may refuse to run with certain parameters, or run with modified values of these parameters, but they do not **_overwrite_** these parameters. Please bear with me through the following example.
_Example: The method `str.ljust(width)` as defined [here](https://docs.python.org/2/library/stdtypes.html#str.ljust) takes the width parameter. It compares this parameter to string length and produces a new, internal parameter (which may or may not be equal to the original parameter supplied by the user). It operates on the string according to this internal parameter, then discards it when it returns. It does not modify the original width parameter in any way. This is relevant when you run this code, for example:_
`dev1 = 'nikohansen'`
`dev2 = 'dtusar'`
`str_width = 8`
`print(dev1.ljust(str_width))`
`print(dev2.ljust(str_width))`
_The first call to str.ljust() returns a string with 10 characters, although the original parameter is 8. The second call returns a string with 8 characters, as intended.
If, however, this method somehow modified the original parameter during the first call, the second call would return a string with 10 characters. This is undesirable._
- cocopp **_overwrites_** the parameter `foreground_algorithm_list` by invoking its `extend()` method. It is using `foreground_algorithm_list` to **_save_** the arguments passed to it, for the length of the interpreter session.
- Therefore, by calling `cocopp.main()` with some arguments, the user inevitably (and possibly unintentionally) modifies program behavior for every subsequent call.
- Thus, in this use case, the code `genericsettings.foreground_algorithm_list.extend(sortedAlgs)` produces undesired effect.
- If there is a use case where this effect is **_desired_**, then this can be called an **_undesired side effect_**, and code can be added to remedy it. This is why I requested an example use case from you where this effect is desirable.
- If there is no use case where this effect is **_desired_**, then this is just errant code, and should be corrected directly on spot.
- When correcting errors, the root cause should be identified and addressed directly. Otherwise, any addition or modification elsewhere has to be justified as "This is here because there was this errant statement somewhere else that was producing undesired behavior.", which, I'm sure we'll agree, is fundamentally wrong.
- Your suggestion, i.e. re-initializing `foreground_algorithm_list` to the empty list in `rungeneric.main()`, **_does_** solve this issue. But then, in its value in `genericsettings.py` will always get overwritten before its contents are referenced when `cocopp.main()` is called. It will effectively cease to be a parameter -or setting, if you will- and become an ordinary persistent variable instead. So there will be no meaning in having it in `genericsettings.py`.

Am I making sense?

**Comment by nikohansen** [comment] 2017-08-10 09:41
`cocopp.genericsettings` is used to reflect the current parameter setting in the module `cocopp`. As it stands currently, these parameters can possibly change at any point in time after `cocopp` has been imported. The usecase you are asking for is _from within a Python shell_ (see some rather [outdated usage examples from with an IPython shell here](http://coco.lri.fr/COCOdoc/pp_interactive.html)) or within a Python script, which is supposed to become a major usecase.

The user may want to call a specific method in the module (e.g. `pprldmany.main` which calls `ppfig.get_plotting_styles` which uses `genericsettings.foreground_algorithms_list`), but before that they want to adapt parameters in `genericsettings`. The advantage of this designs is that not each and every method of the `cocopp` module needs a long list of (often repetitive) input parameters. Many figures may have (often the same) foreground and background algorithms displayed.

Of course, any suggestions to improve the code design are always welcome.

**Comment by nikohansen** [comment] 2017-08-25 10:57
What is the current status of this issue, what still needs to be done?

**Comment by islandblue** [comment] 2017-08-28 14:47
Resolved in islandblue-issue1472 branch. Can be closed after #1507 is merged.

**Closed** 2017-08-29 13:43 UTC
Labels: Code-Postprocessing, Priority-High
