### ISSUE TITLE
test coverage testing the correct implementation of the bbob testbed

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#852] opened 2016-03-17 20:05 UTC
Apparently, the tests only cover random points within the domain of interest. That is, the penalization outside of the domain, which is quite important, for example, for f5 (linear) and even decisive for f20 (Schwefel), has never been tested. Therefore the test coverage must be expanded beyond the domain [-5,5].

**Comment by oaelhara** [comment] 2016-03-23 09:50
Is doubling that domain length (to [-10,10]) enough?

**Comment by ttusar** [comment] 2016-03-23 09:52
We have just extended the ROI to [-100, 100]^D (see issue #860), so I would propose to use at least as much for the tests.

**Comment by oaelhara** [comment] 2016-03-23 10:58
Okay, thanks.

It seems we might have a "big" problem in `test_coco.c`,` line 107`:
the return value of `fscanf` is expected to be 3 when it should be 4, this means that no integration test is run!!!
When I correct this, I see a 66.67% failure rate:

       5        0 FAILED expected=-2.01429400e+02 observed=9.53470894e+01 problem_id=bbob_f001_i51_d02
       5        1 FAILED expected=-1.94502200e+02 observed=8.88626333e+01 problem_id=bbob_f001_i51_d02
       5        2 FAILED expected=-1.70046100e+02 observed=1.36879759e+02 problem_id=bbob_f001_i51_d02
       5        3 FAILED expected=-1.95041700e+02 observed=8.99170329e+01 problem_id=bbob_f001_i51_d02
       5        4 FAILED expected=-1.85728700e+02 observed=1.21663858e+02 problem_id=bbob_f001_i51_d02
       5        5 FAILED expected=-1.92642400e+02 observed=9.17501218e+01 problem_id=bbob_f001_i51_d02
       5        6 FAILED expected=-1.86722200e+02 observed=9.28581897e+01 problem_id=bbob_f001_i51_d02
       5        7 FAILED expected=-1.48556400e+02 observed=1.28868145e+02 problem_id=bbob_f001_i51_d02
       5        8 FAILED expected=-1.83113300e+02 observed=9.60039116e+01 problem_id=bbob_f001_i51_d02
       5        9 FAILED expected=-1.79748400e+02 observed=1.09236296e+02 problem_id=bbob_f001_i51_d02
       5       10 FAILED expected=-1.73973800e+02 observed=1.20646203e+02 problem_id=bbob_f001_i51_d02
       5       11 FAILED expected=-1.30901000e+02 observed=1.70965684e+02 problem_id=bbob_f001_i51_d02
       5       12 FAILED expected=-2.00012200e+02 observed=9.72407859e+01 problem_id=bbob_f001_i51_d02
       5       13 FAILED expected=-1.68843700e+02 observed=1.32837971e+02 problem_id=bbob_f001_i51_d02
       5       14 FAILED expected=-1.99098700e+02 observed=1.01794591e+02 problem_id=bbob_f001_i51_d02
       5       15 FAILED expected=-1.93599000e+02 observed=1.13146565e+02 problem_id=bbob_f001_i51_d02
       5       16 FAILED expected=-2.00745300e+02 observed=9.70090585e+01 problem_id=bbob_f001_i51_d02


Can anyone confirm this please?

**Comment by ttusar** [comment] 2016-03-23 12:14
The bug is mine, I'll have a look.

**Comment by ttusar** [comment] 2016-03-23 12:41
Ok, so I think the problem is not that the functions really produce different results than expected, but that there is a problem in the mapping from "old" problem indices to new ones. I could swear I fixed this already, maybe it got lost in one of the branches... In any case, I will take care of it ASAP.

**Comment by ttusar** [comment] 2016-03-23 14:20
Solved! The problem was that the test was using default instances for the `bbob` suite instead of explicitly saying `instances: 1-15`. While the test wast turned off, the defaults changed... Another lesson learned!

The fix is now being tested, I will close the issue once I push the changes to the development branch.

**Comment by ttusar** [comment] 2016-03-23 14:55
The changes are now in the development branch!

**Comment by oaelhara** [comment] 2016-03-24 13:08
Works fine, thanks :).

However, new `bbob2009_testcases.txt` files I generate using `generate-bbob-tests.R` fail some tests. I even got:
`Assertion failed: (y[0] + 1e-13 >= problem->best_value[0]), function f_rastrigin_evaluate, file code-experiments/src/f_rastrigin.c, line 48.`

It (`generate-bbob-tests.R`) is the file we're supposed to use to generate the test-cases no? 

P.S., In order to run it, I needed to download `soobench` from [https://cran.r-project.org/src/contrib/soobench_1.0-73.tar.gz](url). Which seems to use the old C implementation that is put in a folder `soobench/src/`. It should probably be added to the repository no?

**Comment by ttusar** [comment] 2016-03-24 14:59
I hope this question is not addressed to me, because I don't know what to respond...

**Comment by oaelhara** [comment] 2016-03-24 15:53
No no, don't worry. Maybe @nikohansen

**Comment by oaelhara** [comment] 2016-03-25 10:36
And would it make sens to test the integrity on two sets of data, say:
`bbob2009_testcases.txt`
and
'bbob2009_testcases_extended_DOI.txt'
just to still have enough points tested within the DOI

**Comment by ttusar** [comment] 2016-03-29 11:04
I've made a new test case called `bbob2009_testcases2.txt` to test the compatibility between the old and new code. It contains 100 vectors from `[-100, 100]^d` and is called in addition to the existing one. It only showed one problem in python (none in C), which was due to precision. Now this is fixed (precision 4e-6 is now used in both python and C to test that two values are "almost equal"). 

This issue can therefore be closed, I just have a question. @nikohansen The test case is produced using a short python script that in turn uses the old python code. Where should I put this python script and should I add the old python code too? Possible folders:
- code-experiments/tools  
- code-preprocessing

Of course, there might be some other suitable place we haven't thought of...

**Comment by brockho** [comment] 2016-03-29 19:21
As I said earlier today, I would have put the script together with the tests together with a simple comment where to find the old code.

**Comment by brockho** [comment] 2016-03-29 19:22
[changed the assignee to give credit to @ttusar]

**Comment by brockho** [comment] 2016-07-06 06:19
@ttusar: can we finally close this issue?

**Comment by ttusar** [comment] 2016-07-06 09:47
I'm afraid not - I don't think I committed the script to create the new test cases and now I can't find it anywhere :(

**Comment by ttusar** [comment] 2016-08-12 08:22
I finally found it. I added the script to the `code-experiments/test/integration-test` folder.
This issue can now be closed.

**Closed by ttusar** 2016-08-12 08:22 UTC
Labels: Code-Experiments, Priority-Critical, Tests & CI
