### ISSUE TITLE
Figures LaTeX templates messed up (matplotlib version 2.0)

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1404] opened 2017-06-09 10:57 UTC
While working on #1171, I realized that the recent changes in matplotlib with its new version 2.0 messed up almost all our figures within the LaTeX templates due to trimming and clipping (the HTML output seems okay). We should definitely check and adjust all templates and the postprocessing accordingly before the next BBOB workshop.

**Comment by nikohansen** [comment] 2017-08-31 19:38
FTR, the font-bug went away in the latest `matplotlib` version`2.0.2`.

**Comment by nikohansen** [comment] 2017-09-06 13:51
Closing as duplicate of #1502

**Closed by nikohansen** 2017-09-06 13:51 UTC
Labels: Code-Postprocessing
