### ISSUE TITLE
increasing number of instances

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#733] opened 2016-03-02 11:29 UTC
Hi,

I would like to increase the number of instances for the functions. The goal is to reduce noise in the tuning/development stage. It is currently really hard to get stable estimates for the multi-modal functions, e.g. repeating with a different seed can completely change the order of algorithms, especially for algorithms that do not handle multi-modality well(e.g. strong dependence on initialization). This does not make any sense.

Is this possible?

**Comment by ttusar** [comment] 2016-03-02 12:49
It is possible to increase the number of instances. You just need to call the suite with:
````
suite = coco_suite("bbob-biobj", "instances: m-n", "")
````
and set `m` and `n` according to your wishes. However note that instances over 10 haven't been yet fixed for the `bbob-biobj` suite, which in practice means that some pre-processing will be run once per suite initialization. This won't affect your experiments, but just so you know what is going on.

**Comment by nikohansen** [comment] 2016-03-02 13:37
Having said that, it won't help much, if at all, to increase the number of instances for which the experiments are conducted, because, AFAIK, we have by now not yet established the means to display the results on new or arbitrary instances. Correct me if I am wrong.

**Comment by nikohansen** [comment] 2016-03-02 14:00
See also #722: the method of choice to solve this problem, at least at this moment in time, are restarts within the runs.

**Comment by ttusar** [comment] 2016-03-02 14:53
Good point, postprocessing is done only for instances 1-5.

**Comment by nikohansen** [comment] 2016-03-04 16:24
There is another method of choice to solve this problem, given you have a randomized algorithm. Run the algorithm several times on the very same suite. Collect all output folders in a single folder to give as argument to the post-processing. Like this you can generate as many randomized repetitions as you want to get a stable estimated of the runtimes.

**Comment by Ulfgard** [comment] 2016-03-04 21:37
Hi,

thanks for the answers. So increasing the number of instances does not make sense right now as post-processing does not get it. okay.

Restarting the runs is not equivalent to more runs, especially for the ECDF plots: On convex function pairs it is likely that most of the iterations of a repeated run will not generate a point which will increase the hyper volume. It is also kind of not helpful if the algorithm to be tested already uses restarts and one wants, for example, tune the restart criterion. 

Runtime plots will also not show any differences as soon as the first sample pushes the volume above the threshold.

The collecting argument does not work, either. currently the post-processing will bail out if the same function/dim settings can be found in different sub-folders, even if the total number of trials is < 5. I encountered that in #707.

Should i mark this as closed in the sense of wontfix?

**Comment by nikohansen** [comment] 2016-03-05 01:33
> Restarting the runs is not equivalent to more runs, 

not equivalent, but for most practical purposes within the COCO performance assessment pretty similar, in particular if you have a limited budget anyway and/or effective termination conditions.

> especially for the ECDF plots: On convex function pairs it is likely that most of the iterations of a repeated run will not generate a point which will increase the hyper volume. 

sure, and? 

The original demand was to get a more stable performance estimate on multimodal functions, which can be well addressed by restarts, in particular if the success probability is low. 

> The collecting argument does not work, either. currently the post-processing will bail out if the same function/dim settings can be found in different sub-folders, 

I would consider this to be a bug.

**Comment by nikohansen** [comment] 2016-03-18 11:37
> The collecting argument does not work, either. currently the post-processing will bail out if the same function/dim settings can be found in different sub-folders,

@Ulfgard , can you be more specific about the problem (bail out) you observe, as it seems to work for @dtusar , [see here](https://github.com/numbbo/coco/issues/745#issuecomment-197958025)

**Comment by brockho** [comment] 2017-09-07 14:57
Seems to be a duplicate of #745 to us (@nikohansen, @dtusar, @islandblue, @brockho).

**Closed by brockho** 2017-09-07 14:57 UTC
Labels: bug, Code-Postprocessing, Priority-High
