### ISSUE TITLE
Negative hypervolume values

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#813] opened 2016-03-13 19:11 UTC
On some functions it is quite possible to reach better hypervolume values than the ones given as a reference. While such better/negative values are logged in .dat files, they are not displayed in plots. 
I would like to display them to better understand how my algorithm works. As Niko suggested, I tried to modify bbob_pproc/genericsettings.py file. More specifically,  I modified class GECCOBiobjBBOBTestbed as follows

self.pprldmany_target_values = targetValues(10**np.arange(0, -5, -0.2) -1.327070185389578e-004) # possibly changed in config
self.rldValsOfInterest = (1e-1, 1e-3, 1e-5) # possibly changed in config
self.ppfvdistr_min_target =  -1.327070185389578e-004
self.functions_with_legend = (1, 30, 31, 55)
where -1.327070185389578e-004 is the smallest relative hypervolume value.  
It does not plot the results after ~2000 times 20-dimensions when first negative values were found. 
I attach 
[SMSEMOA_on_bbob-biobj-060.zip](https://github.com/numbbo/coco/files/171183/SMSEMOA_on_bbob-biobj-060.zip)
[pprldmany_20D_noiselessall (4).pdf](https://github.com/numbbo/coco/files/171184/pprldmany_20D_noiselessall.4.pdf)

In hope that my mistake is quite obvious and does not require any debugging, I ask you to please let me know how to modify the file to plot negative hypervolume values/targets.

**Comment by nikohansen** [comment] 2016-03-14 12:05
Did you either re-install the post-processing (`python do.py install-postprocessing` in `coco`) or run it from the `coco/code-postprocessing` subfolder? 

I get the following:
<img width="565" alt="screen shot 2016-03-14 at 13 02 00" src="https://cloud.githubusercontent.com/assets/7316439/13743952/2715da8c-e9e5-11e5-9148-3238b4abe206.png">

That is, negative targets are generated (I also printed them), but they are not displayed as being hit. @dtusar , any idea why this is the case?

**Comment by loshchil** [comment] 2016-03-14 12:25
I had the same plot as you show.

**Comment by nikohansen** [comment] 2016-03-14 12:25
It seems that `DataSet.detEvals` returns `nan` for negative targets, which must be considered as a bug.

**Comment by nikohansen** [comment] 2016-03-14 13:01
It looks like the read-in data set does not correspond to `.dat` file, but ignores negative values. I don't see exactly how it works, but we would need to read in all targets which are later needed in the respective testbed setting. If they don't match exactly, at least the next smaller target must be read in.

**Comment by dtusar** [comment] 2016-03-14 19:43
The data set can now contain also negative target values, but are still different than the values in testbed settings.

**Comment by Ulfgard** [comment] 2016-04-03 16:51
regarding the newest release: can it still be expected that the reference value of sphere is a lower bound? I ask because there is an analytic solution. the fact i am still observing negative values and because of another thing:

when we add the volumes of the (possibly) 10^7 points of the hypervolume, every summand is computed as a term of the form (x_2-x1)*y_1. Thus, we feel the effects of catastrophic cancellation: subtracting two close numbers will result in a much smaller numeric precision. for double it can half the significant digits from 16 down to 8. Thus having a target of 10^-8 could be well within the numeric error bound.

**Comment by nikohansen** [comment] 2016-04-04 16:34
> can it still be expected that the reference value of sphere is a lower bound? 

I don't think the reference value is meant to be a lower bound. The value is also not meant to be used by the algorithm in any way or shape. I see your point though, that it has some appeal to set the reference value to the lower bound for the double sphere of the `biobj` testbed. This would mean however, and less appealing, that we should also change the target value computations specifically for the double sphere function. 

> when we add the volumes of the (possibly) 10^7 points of the hypervolume, every summand is computed as a term of the form (x_2-x1)*y_1. Thus, we feel the effects of catastrophic cancellation: subtracting two close numbers will result in a much smaller numeric precision. for double it can half the significant digits from 16 down to 8. Thus having a target of 10^-8 could be well within the numeric error bound.

I agree that we might see huge cancellations when we want to compute a hypervolume with large precision, or, from as many as millions of solutions. I don't see (a) why this would become a real problem and (b) a way how to prevent this, because all hypervolumes to start with are in the order of about 1. I am also not aware that there is a target of `10^-8` actually in use. The smallest HV difference of relevance is, at this point in time and to the best of my knowledge, `10^{-5}`.

**Comment by Ulfgard** [comment] 2016-04-04 17:22
Hi,

Just so that we are at the same page: 

- the generated tables pptable2_*D_noiselessall*.tex have target values 10^-7 which are reached with long running times.
- files as bbob-biobj_f01_d02_hyp.dat contain in my case stuff labeled "indicator value" marked as 10^-8

are these files relevant for the generated plots and do I understand them correctly as the reached target values? If yes: the generated pprldistr plots are consistent with the labels (otherwise i would expect to see a straight line as soon as all trials reach accuracy 10^-5)

should i send you bbob-biobj_f01_d02_hyp.dat  to reproduce this?

**Comment by loshchil** [comment] 2016-04-04 17:41
Have a look at the targets used for plotting, they also include negative
targets.
10e-5 is the lowest order of change that will affect the curve (also for
negative values)
the targets stored in the files are not the same as the ones used for
figures, however, they overlap
for many multi-modal problems you will see that their typical order is
+1e-3 and then -1e-3 or so because the hypervolume references are still not
good enough. If 1e-8 will be used then multi-modal functions might have a
much lower relative weight in the aggregated ECDF curve
I guess the organizers should have a look at what is the visual effect of
different target ranges once the first edition is finished.

**Comment by nikohansen** [comment] 2016-04-04 17:53
> the generated tables pptable2_D_noiselessall.tex have target values 10^-7 which are reached with long running times.

I believe this target is outdated, but I could be wrong. Even if this is the most difficult target, as the second difficult target is at least `10^-5`, this would still mean that relevant target differences are in the order of `10^-5`. 

> files as bbob-biobj_f01_d02_hyp.dat contain in my case stuff labeled "indicator value" marked as 10^-8

AFAICS this is fine. The recording granularity has been chosen to be finer than the granularity used in the assessment.

>  If yes: the generated pprldistr plots are consistent with the labels (otherwise i would expect to see a straight line as soon as all trials reach accuracy 10^-5)

You might want to paste a picture here, to be sure what we are talking about. In the most prominent ECDF plots, with the current post-processing code, 7/58 targets are more difficult than `10^-5`, the most difficult target  is `-10^-4`, and all target differences are `>=10^-5`.

**Comment by Ulfgard** [comment] 2016-04-04 18:07
okay. I think i understood it now. to summarize:

- The reported values are on a different grid, e.g. only a subset of the stored values are used. So numeric errors in those ranges are not relevant, because they do not influence the final plots.
- Because there is uncertainty in the reference values, the target set also contains negative values
- This explains why most pprldistr plots end around 0.9 while I can reach nearly 1 on some of the harder functions
- This also means that a target function with a well approximated reference value has a lower weight in the summarized pprldistr plots, because some targets can not be reached.

**Comment by nikohansen** [comment] 2016-04-04 18:25
the summary looks about right to me, while

> This also means that a target function with a well approximated reference value has a lower weight in the summarized pprldistr plots, because some targets can not be reached.

this effect is rather marginal, that is, they still get a weight of at least 88 out of 100.

**Comment by brockho** [comment] 2016-04-04 22:45
> Just so that we are at the same page:
>
>    - the generated tables pptable2_D_noiselessall.tex have target values 10^-7 which are reached with long running times.
>    - files as bbob-biobj_f01_d02_hyp.dat contain in my case stuff labeled "indicator value" marked as 10^-8

You have been correct with your observations, @Ulfgard. Since we do not (yet) provide LaTeX templates for 2 or more algorithms and the bi-objective test suite, the tables and figures generated in this case have not been checked as careful as they should have. The targets in the tables were therefore set the same for the single-objective and the multi-objective case and thus, not appropriate for the bi-objective `bbob-biobj` test suite. This has been corrected for all tables now together with the corresponding captions (available already in the development branch and soon in the next release).

Note that the plots for 2 or more algorithms have also not been checked carefully yet and might not always display what the caption says in the html output.

**Comment by nikohansen** [comment] 2016-05-16 10:56
Can this be close, as the bug-part has been resolved?

**Comment by loshchil** [comment] 2016-05-16 13:18
Yes, I think it can be closed.

**Closed** 2016-05-22 18:10 UTC
Labels: bug, Code-Postprocessing
