### ISSUE TITLE
activate test_suites

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1234] opened 2016-11-30 00:05 UTC
I factored out the regression tests of the suites in `do.py` from `test_python()` into `test_suites()`. 
What needs to be done now is to initiate this test automatically. It can be done by

```
python do.py test-suites 2 10 20
```
where the numbers are optional and refer to a data set with the respective number of solutions tested per problem, default is 2 (for a very quick test), it can be all three to test 32 solutions (for overnight test). The numbers refer to the respective test data which must be present under `test/regression-test/data`.

**Comment by dtusar** [comment] 2016-11-30 09:48
I can add this to the tests. On Jenkins I don't like having `do.py` calls with parameters since then folders with quotation marks are created. I will add a python `do.py test-suites-all` option which will test all the 32 solutions.

> The numbers refer to the respective test data which must be present under `test/regression-test/data`.

I'm not sure if I understand this correctly but if we want to run this test automatically the data must be created during the test.

**Comment by nikohansen** [comment] 2016-11-30 11:45
The data created during the test are compared against previously generated data, which are part of the repository now. I couldn't think of a better solution.

`test-suites-all` should maybe rather be called `test-suites-full`.

**Comment by dtusar** [comment] 2016-11-30 11:51
> The data created during the test are compared against previously generated data, which are part of the repository now. I couldn't think of a better solution.

This should work.

> test-suites-all should maybe rather be called test-suites-full.

OK.

**Comment by dtusar** [comment] 2016-12-21 15:01
@nikohansen On my computer the regression test for 10 solutions fails. If I run `python do.py test-suites 10` I get this error

```
PYTHON  test_suites.py 10 in code-experiments/test/regression-test
ERROR: return value=1
using file data\regression_test_10data_for_suite_bbob.py with 21600 test cases B
BOB suite problem f12 instance 58 in 2D (177, (1447.3149385050367, -830.32704880
85931)) (1.7499057709942032e+141, []) 6.09043250958e+67
Traceback (most recent call last):
  File "test_suites.py", line 83, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 55, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```


Can you check this before I add the `test-suites-full` option?

**Comment by nikohansen** [comment] 2016-12-23 18:58
I committed a fix for the above assert in the `development` branch. That doesn't guaranty that the remaining tests go through, so this need to be checked.

**Comment by dtusar** [comment] 2017-01-06 15:00
Similar error but for a different instance and dimension:

```
PYTHON  test_suites.py 10 in code-experiments/test/regression-test
ERROR: return value=1
using file data\regression_test_10data_for_suite_bbob.py with 21600 test cases B
BOB suite problem f12 instance 60 in 10D (1259, (-210.53303892552228, -462.08459
68937024, -290.7828003528346, 38.77659627429867, -385.35555946990524, -535.84226
099009, -28.798228905496824, 18.107131167883104, -40.292707650687284, -148.38956
205454977)) (1.2219569577863538e+76, []) 1.2963795943e+27
Traceback (most recent call last):
  File "test_suites.py", line 86, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 58, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```

**Comment by brockho** [comment] 2017-01-13 15:32
I get exactly the same error than @dtusar (after pulling from the development branch). Setup: Windows 7 with Python 2.7.11, Anaconda 4.0.0 (32-bit) but without cygwin (@dtusar will most likely have cygwin).

**Comment by dtusar** [comment] 2017-01-13 15:57
Yes, I have cygwin.

**Comment by brockho** [comment] 2017-01-17 10:01
On the linux slave, we get now also problems with `f17` (Schaffer F7) within the new `bbob-biobj-ext` suite, although it runs through on the Windows slaves and also on my Windows machine. Here the error from the linux CI slave:
```
PYTHON	test_suites.py 2 in code-experiments/test/regression-test
ERROR: return value=1
using file data/regression_test_2data_for_suite_bbob.py with 4320 test cases done in 2.6s
using file data/regression_test_2data_for_suite_bbob-biobj.py with 6600 test cases done in 10.1s
using file data/regression_test_2data_for_suite_bbob-biobj-ext.py with 11040 test 
   cases bbob_f001_i02_d40__bbob_f017_i04_d40 (4670, (-344.5039541883759, 1002.3787011082846,
   -1846.3777021329383, -1178.1051461362956, -2367.5636249963177, 243.98049666725245, 
   -4664.386283738969, -2753.3570278473594, 2236.8259564681216, 2001.0517739922507, 
   4410.797468217011, -3873.518790171759, -1868.480458210121, 3119.7781999648073, 
   -2232.0521637085512, -2143.1138309617395, 287.86014597820844, -1746.319527717172, 
   1805.4791117071786, 8311.531980795122, 1222.7067858852604, -1445.1888095914162, 
   270.7474730872047, 2695.4358045171853, 2963.708871777713, 1714.8398085915446, 
   -790.9201918390233, -1127.9447533015175, 2443.6027029822994, 2595.1189331969854, 
   526.0054347948357, 2465.587422237548, 3338.497180085664, 2482.031464867961, 
   2601.968206920175, 95.07104453139634, -3481.063907997643, -2087.945104725294, 
   -3127.481721176605, 3254.966424795819)) ([287089787.64410305, 3.1488536291123374e+39], 
   []) [  2.87089788e+008   9.76803002e+118]
Traceback (most recent call last):
  File "test_suites.py", line 86, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 58, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```

**Comment by nikohansen** [comment] 2017-01-17 13:02
I adapted again the conditions that the above examples pass, committed as https://github.com/numbbo/coco/commit/bbeb0340ca0d91408add4a99e1cf82f36231dcd7

**Comment by nikohansen** [comment] 2017-01-17 13:08
For testing I added a new branch which relaxes the condition further, such that the test always passes if both absolute values are above 1e21 and they have the same sign, see branch https://github.com/numbbo/coco/tree/relaxed-suite-regression-test

**Comment by brockho** [comment] 2017-01-19 15:47
Now, the `bbob-largescale` testsuite produces some errors on this test in the CI:
```
PYTHON	test_suites.py 2 in code-experiments/test/regression-test
ERROR: return value=1
using file data\regression_test_2data_for_suite_bbob.py with 4320 test cases done in 1.9s
using file data\regression_test_2data_for_suite_bbob-biobj.py with 6600 test cases done in 7.0s
using file data\regression_test_2data_for_suite_bbob-largescale.py with 4320 test cases BBOB
 large-scale suite problem f17 instance 4 in 40D (603, (-3229.465218631997, -6126.744730241225, 
-8054.825601840458, 3783.1112083924163, 5611.551763172921, -1888.2911057929184, 
765.4843521062418, 1007.7071688409779, 6315.9553347947085, 7049.058748120774, 
4156.92626694278, -2777.9187554287314, 5806.268984182716, -515.5412995868968, 
1558.0412329869657, 2242.3683584899836, 6576.388442833041, 780.9883864945367,
 -1189.9058472186944, 9718.19881246928, -6847.0249565599515, 3122.953151036975, 
4532.068038257392, -4938.2347867939625, -2522.9614806016234, 2306.0270358716202, 
313.50354297150756, -2881.5138806052105, -3405.7264624263803, -6603.531067599466, 
-1550.103410097061, -3133.2412439892814, -4592.999271320448, 3241.327674577217, 
5952.004623798708, -2431.3494206603323, 9379.319693095294, -1084.8850719410375, 
-2768.6019144748097, 1463.3580442343373)) (5.449929602038278e+136, []) 6.96081091792e+29
Traceback (most recent call last):
  File "test_suites.py", line 88, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 60, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```

**Comment by brockho** [comment] 2017-01-19 15:49
On the linux CI slave, this it the error (different dimension, function, and instance):
```
ERROR: return value=1
using file data/regression_test_2data_for_suite_bbob.py with 4320 test cases done in 2.5s
using file data/regression_test_2data_for_suite_bbob-biobj.py with 6600 test cases done in 9.6s
using file data/regression_test_2data_for_suite_bbob-largescale.py with 4320 test cases BBOB large-scale suite problem f7 instance 13 in 640D (1902, (-3.711545253961496, 1.111372380496454, 3.323464073907975, 3.9406870892830836, -1.6487973913978862, -0.694080413284366, 4.316115397429049, -1.220157793461376, -0.6323685461344304, 0.05120507927626209, -3.5503714346441995, 0.8013890356092034, -3.697102913835342, -1.2997776666162313, 2.8992001486500247, -0.9764082891282462, -0.38122569194153016, 2.405890915358153, -1.1144589599498176, 0.21425428054619805, 3.0508507485343417, 1.3786872925944496, -2.6659583978214747, 1.4262996924279518, 1.7260037319141002, 0.02398502220686118, 0.10226148149003064, 7.023916689853112, 1.2179073962532259, 1.8197028908660553, 3.7144700654623675, -0.7448517273104522, 0.6164932736552049, -1.4864143009203283, 0.7631932415810072, 0.6449926667433292, 0.6113215821005775, -1.85581290465036, 1.2639202177360565, -6.190923168100261, -0.9492441144539455, 1.905370384083705, 0.6519732529830302, -1.8089337631255118, 4.378101185561727, -1.882303921514131, -0.7352453512044025, 3.340620993470822, 0.6631141089270747, 1.8335608980746891, 4.999782791704211, -4.860046281522934, 2.907740823691381, 2.528402994187483, 0.6158219661877655, -1.9966578534716943, 5.635634057331433, -2.6561745942706896, -3.5900563775322256, -0.9135158683097214, -1.4996665114546648, -1.071869049988796, 0.13169522185196111, 1.664296257489899, 0.4646798668054646, 0.03918802950940883, 0.49708045182557825, 5.713648857013577, 7.145195053066974, -1.2519110890211698, -1.2483949677903636, -0.10248101151724805, 5.481469841521034, -1.8460770967424494, -1.1377880512275014, 0.5364857657349236, 0.6721037396032714, -3.668033454762296, 2.2205192977923796, 0.4254632584012414, 0.24740172993482626, -4.727974781348428, 1.3134507299019265, 0.9701592623734249, 1.9572898025650733, 2.0855789750781004, -4.058036728838636, 0.8716369411439271, -4.905481293853654, -2.2601632343880795, -2.4664492363051234, 2.275521223169399, -0.70707350179469, -3.000575703947298, 2.9861088497599018, 3.8976513066895255, -3.7262346887265916, 0.7953589759801483, 1.0030085785007323, 1.0427445359249883, 0.020367538473361195, 0.6874248691344714, -1.3933086791692069, -1.4598970368813817, 2.47124140273076, 1.5432644941678335, -5.810481208484253, 0.5626699017653768, 4.342119176011529, 2.237706061328632, -0.6199743030790337, -1.183266527022372, 1.5116518521454527, -2.723729438890436, -1.4647161676388556, -4.204946825022444, -0.33360436071854216, 0.025827233125477824, 6.89285781421084, -4.209591499529986, -1.3197613722348103, -2.2229106993408423, 2.479496414887981, 1.514274317192858, 5.727679020746296, -0.0005650173308873971, -1.6957379851108991, -1.073092494851796, 3.945065536261811, 3.285192225961159, 0.36190945636082655, -0.14138060131079497, 2.4030982677164325, -0.45951950903549116, -3.79698946975909, 2.7423400877968644, -0.8701547128246582, -0.9981280243783974, -2.8060474173800705, 1.2136346445285495, -2.608092122897559, 4.543738723648018, -6.3222496449236925, -1.170351111868178, 3.618300708285514, -2.3296151406339867, 2.102251834599364, -7.091627476215944, 1.0478204525287562, 1.291572580897808, -2.285571042488334, 1.21148964069974, -0.538431639924416, 0.422673258601553, -2.433061519259232, -0.8159779736950238, -0.6859327502219236, -2.418208700525798, 0.39198686479761713, 5.02118882242985, 2.1882122916497577, -1.6385437415566395, -3.013095695048716, 6.576449116120276, -1.682717933065174, -2.1459075650174935, -0.925820315375772, -0.8658429208839306, 0.054058575622497065, 0.8919795768062857, -1.763330398251508, 0.08372709940389196, -1.3502087099894817, -4.966974399269111, -3.007480663244445, -2.241960076778952, 0.28016074085270204, 1.933629005200304, -3.2720727067218864, -0.398563181396539, 3.3674737691025634, -1.3712149637283726, -2.4538869744512595, -0.9080756266470555, -2.7107488797454886, 0.6646755615432133, 5.466793595135428, -1.8066011475254464, 3.179088328311554, -4.777915416296895, 3.0880268603119276, -0.3556768889359851, 3.130787900254699, 7.074409834164658, -2.2712650537211707, 0.1643920213109986, 0.7142424244700248, 0.6206518278248528, -2.3841447399477422, -4.5295507463984475, -0.03922399226620539, -2.5958490328854045, 3.719162681514655, -1.6749752044014876, 3.9315848177801245, -1.5536114681315978, 4.848176746749544, 4.646059759024366, -3.5329560940870866, -5.422486446499472, -5.071574336056855, 1.026239437450931, -4.3095976519112265, 1.176748779900203, 0.9780151144800349, -2.783924688869648, -0.991877744715512, 5.5599206680399185, 5.2584478657104805, -5.095867861822361, 0.30903051915231783, -6.5909590103519005, -1.374790851995979, 0.5508964974193181, -0.04329691943243343, -0.14479659349587123, -1.7964013117090125, -4.643213001165371, 3.252727598234743, 2.5971314188484502, -1.677338604963282, -4.648998024408323, -2.6661826572037217, -1.2394443432570237, 4.29842881272375, -0.5304021129952052, 6.636024957446616, 5.329486286913577, 2.773753842186265, 0.012136562965972547, 0.7677396841765962, -2.6710862395807062, -4.545816672825823, 2.635078135320853, 0.2240625819257562, -5.251983315260015, -5.721017773843747, 0.9977068064159511, 3.15842498412932, 2.9350496394955896, -1.4827047264995084, -1.9273237993508432, -2.064891302751703, -0.3066440542838461, -0.5541369078074277, -3.311518327265553, -0.18382930427066657, -3.9132968306878353, 2.87808912358521, -0.27028623126264373, 4.257367798362294, 0.2771746422972257, 0.42863817774566115, -2.5981099172154583, -8.079761854935157, 1.1828247487260997, -2.9418286385172596, 0.7854486923052763, -0.6906224328842918, -4.382301318028266, -2.204468372247813, -5.005793346029882, -0.929604584880248, -5.685293139607756, 0.16739309908685987, -5.510664143847004, -2.1516053872253216, -4.188381212527275, 2.835774404018432, 3.8368432931104084, 3.2221886215673794, -4.636154334213913, -1.7371111856389574, 1.8520622631949595, 2.8710910254138318, 2.055079377376285, -1.0281422129800342, 0.21585844980695187, -0.9108419009814214, -1.0508599997246786, 1.4975647229997873, 2.486077834649759, 0.2021958488437169, -2.6208076518195305, -4.299476019503077, -0.05152105077381592, -0.9690212142972374, 1.880916691580476, -1.8385589653760788, -3.2327545998289255, 2.1956267455302063, 0.974692357158673, 0.801182245553635, -4.7715186281922835, 0.03925606324784927, 2.7698816593768063, -3.0120858371901305, -3.0395280837257017, -1.4462352744139344, -3.7371995596978254, 4.640526153511151, -0.2984377408593917, 0.4672396537362565, 0.6618294819780418, 0.07625243240321432, -2.8146586548210886, -2.572884180671301, -3.465309197850411, -0.684246243209905, -1.1244925246988615, 6.01892490164497, -0.015224855842929947, 1.7450407552553517, 0.9801404390055114, 0.5386732000711411, 3.4211196744164694, 4.633332897627908, 0.16833419778305664, -2.240558930367108, -0.2318303400725451, -1.654763696539421, 2.432355857138023, -1.1388650727989145, -1.0438418298530274, -2.132351094724697, -0.6777439714992038, -0.5432645443981163, 1.231088425144785, -1.6074791095571535, 1.3335242640636078, -3.2698998998720934, -2.3340533798420444, 0.41486135159110216, -0.5858147137432989, 2.159242356100953, -5.80125098257298, -3.8729195605369133, -3.3825886528940687, 2.928437051328253, -2.325584734632189, 7.930660940852694, 3.0370174596045993, 1.3792841132787421, -2.9309774798131434, -0.3009457587871576, 1.9099302027229978, -0.06635702684239478, 1.0649368798119199, 1.6233668197176723, -3.6100073974412608, -0.7305433200584556, -4.607544446817001, -2.499622130629188, -0.9796996090076782, 0.2417737830318548, 1.1117374232800068, -1.455261261162433, 5.557867232519, -0.758463310419093, -4.818854788013315, -1.0163410889815756, -3.4904522549149166, -3.526582198025937, 4.204458872367016, -0.7757187678738853, -1.0816688448535599, -5.027723324320083, 1.4380329206895297, 2.902375436355408, 0.5254290082762086, -3.554310455447144, 2.4769834723427504, -2.3475874457062944, -4.370247396546507, 5.02581688931579, -5.207762728528188, -5.524695822869492, 0.3037477241310145, 0.4660092303455394, 6.48627306082951, 0.5991016691568922, 0.15566405843908523, -2.421022877629199, 4.182576691702894, -0.2816211044476825, -3.972633775343294, -2.7870248197223817, 1.451533063528717, -0.7243070812715416, -1.203872574441689, -0.8914309805700353, 5.378892927714445, 5.819060663213863, -0.12555887919051434, -1.88782049322126, 2.592565227670823, 0.2987900863748238, -2.5205237817681376, -0.16020644536637496, -0.7975366920642927, 4.760870521554882, 1.0818946499102309, 1.5636350677705975, 0.4500797295206129, -2.0377167923878963, 1.4582250787194662, -1.3580174313222988, 5.229310666667764, 5.933034266834356, -1.9789163565374936, -2.420150817355364, 5.70223655478276, -0.09740517126551726, 1.8225347146540116, -1.5937210606734693, -0.02835667125223794, -1.142364307246624, -3.040711939570243, -2.1870906400283214, 1.432178455434946, -1.0650013157445795, -2.3004080495052044, 0.8206941157793192, 4.088512237915607, -2.6095326110065136, 4.840414667424521, -0.11793789208730977, 4.275447195432848, -2.7925079567062765, -1.1206696909869884, -3.8019465359580527, -0.04710029306698601, 2.6009010958129255, 1.6587475543035064, -2.4287256910304813, 0.5626435983873626, 1.9756901829716564, 1.4291185400815722, 0.012970225345684826, 1.552648555048814, 2.163484479123207, 2.833262536763909, 3.7248805023769127, 5.204854984803481, -0.14167637524420643, -0.5949759554014394, 3.599317078266281, 3.1138514873383425, 6.8680219384442385, 1.6001144035647799, -0.3689887772046676, -1.8336203775375255, 5.082686278951316, 0.9227027274592208, 3.209505530560411, -0.35516416583321864, 1.3306712290735838, 0.3636975092751335, 0.29481840058984915, -2.628832818680391, 0.2659438654506027, -1.0829254564609534, 3.710006042466386, 2.8737329320400127, 1.9421097428412333, 0.45962347444461554, 4.9771338262034055, -1.9521557297106387, -1.1307934935853257, -4.2174198127103, 6.79236573781007, 2.6890904254386756, -3.5628911750996988, 0.2513753178199028, 6.092575945732571, 2.7818125785149386, -0.05411646996470878, 2.974029114427741, -0.41223263000609023, 0.473808109250398, -2.13113891227418, -4.444749120163875, 1.6683082398516977, 2.257576769305172, -0.0973268092486009, 0.15612592298605055, 1.3496554400384042, 3.4374197903774295, -3.419332876322327, -1.5407090133557473, -0.3168524514173456, 1.9933440116729584, -3.1349509385214027, -2.0630990701844625, -0.6712164976487591, -2.243241741294403, 6.1251453079123035, 1.3818278590156774, 2.88632110272439, -2.182255487215293, -3.5759814333845035, 1.622193856280923, 4.184137978342683, 2.6350483280043266, -0.7648931445754915, -0.05357590534776472, -0.5918722755863763, 6.524976432517001, 2.3642272680893526, -5.979005674576087, -1.9703587842804626, 4.070657276235264, -1.9688460121231859, 1.172716972987994, -1.2968474892180717, -0.08059028188480265, -0.7848984508672724, 1.6940487317110082, 0.7222984138693502, 5.395163380870971, -0.29622237381789596, -0.400289704745541, 2.3479184916280103, 1.3897376053170445, -1.8789095356729293, 0.21682668233108635, -0.49299976837263226, -2.331846067298827, 1.1662861455901485, -6.493575391125944, 2.1049228489051797, 0.6921017056784515, -1.17060558757297, 5.375478518966474, -0.6190434894108516, 4.158098226551529, 5.548900511995882, 1.4700005903394358, -0.4366005384517391, -2.038419609120988, -1.2845529603558736, -1.3789806405481508, -2.3589013658481055, 5.930973141752969, -2.413266797942323, 0.5341253588009723, 1.3785934000501237, 2.2988848254049956, -3.7758553542585593, 0.9401269822625776, -4.819783616384518, -0.19438898119337877, -2.2369081754751186, 2.730124106542444, -0.4798781653562179, -1.6955673360370271, -4.185693953814692, 3.728319993170934, -2.6588128176445593, -0.1059937396371486, 0.33900070950401706, 1.3274778628411845, 4.122146010594642, 1.6302463862327006, 0.8030172481177444, 0.4313879851761144, 0.5003336650149163, 4.5970089073280676, 0.036843377283058545, -0.051408489084456194, -1.5393914917170117, 4.2232403393104585, -0.27495128652247963, 0.5240794245776786, -0.2961203405991761, 4.123471864442108, 1.330275549819701, 0.8777711965786898, -3.726532977395987, -2.975354169810705, -2.296303105876398, 1.1349080125512727, 0.6109691874449237, -1.4568750620867055, 3.9794483680031365, -5.056643671431159, 3.507130115510898, 0.24115077417432484, -2.8183722652977363, -1.3716977739597076, 0.09905469381474112, 3.1432519911852785, 1.3945032527314416, 0.3267393268472101, 2.733072537908631, -0.7234882138645928, -6.890991993774195, 3.398957383069539, -1.0549612123287404, -2.627392990552503, -1.7035878621814273, -2.7192527342413753, -2.92555482629382, 0.08539585914523515, -3.4680740467547064, 1.2720112490315516, 0.049431150455691186, 0.033367118829794304, 0.07901390563617001, -3.4358613114208887, 1.601234250886532, 2.3156058380878854, -2.716671404637791, -1.9304528506112955, 3.987772504426795, -4.615544793548555, 3.290036121261872, -1.6144878904438078, 4.680084961489727, -1.5333397297688183, 4.008227493953949, 5.856910282520019, 2.233378059005823, -1.9248066372500539, -1.6248601299318193, 2.2464764228404643, 1.7161267502262454, 0.4088904498408709, -1.076079925114803, -1.8344244951919086)) (5270.34718974349, []) 5146.78691858
Traceback (most recent call last):
  File "test_suites.py", line 88, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 60, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```

**Comment by nikohansen** [comment] 2017-01-19 15:59
This
```
using file data/regression_test_2data_for_suite_bbob-largescale.py with 4320 test cases BBOB 
large-scale suite problem f7 instance 13 in 640D (1902, (-3.711545253961496, ... 
-1.8344244951919086)) (5270.34718974349, []) 5146.78691858
```
looks like a real "bug", in that we these values are essentially different.

**Comment by nikohansen** [comment] 2017-01-19 16:40
`large-scale suite problem f17 instance 4 in 40D` is addressed with commit https://github.com/numbbo/coco/commit/232fc2be2464e25e31cb70a2f1b96aa11d789611

**Comment by nikohansen** [comment] 2017-01-20 09:34
Now the test passes always if both absolute f-values are larger than 1e21 and have the same sign https://github.com/numbbo/coco/commit/f8ab56cef604a648d1336fbbfe6a3f5c8f76fd3e

**Comment by brockho** [comment] 2017-01-23 21:34
I opened  #1291 as a follow up and assigned this issue here the large-scale and bug labels as it seems to be only an issue for this test suite.

**Comment by brockho** [comment] 2017-01-24 22:04
> This
> 
> using file data/regression_test_2data_for_suite_bbob-largescale.py with 4320 test cases BBOB 
> large-scale suite problem f7 instance 13 in 640D (1902, (-3.711545253961496, ... 
> -1.8344244951919086)) (5270.34718974349, []) 5146.78691858
> 
> looks like a real "bug", in that we these values are essentially different.
> 
How comes that this problem does not occur anymore in the latest test on the `devel-test2` branch? I did not see any change in the function source code in the pull request. @oaelhara: any idea?

**Comment by oaelhara** [comment] 2017-01-25 00:13
I'm as puzzled as you are @brockho , I didn't change any code that should directly affect this, not in that commit.
I will try to have a deeper look into it, but I expect to see this error pop-up again.

**Comment by dtusar** [comment] 2017-06-02 13:39
My current error when running `test-suites 10`:
```
PYTHON  test_suites.py 10 in code-experiments/test/regression-test
ERROR: return value=1
using file data\regression_test_10data_for_suite_bbob.py with 21600 test cases B
BOB suite problem f19 instance 63 in 5D f,x = (997, (0.025689137966068393, 0.020
34570303641521, -0.45461271807165743, -0.5868132349492098, -0.6222366768803014))
 stored x,f,con = (234.6779941370806, []) computed f = 107.894609821
Traceback (most recent call last):
  File "test_suites.py", line 92, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 62, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```

**Comment by brockho** [comment] 2017-06-06 12:34
I guess that this is related to the fact that line 57 in `test_suites.py` was outcommented  at some point. The year `0000` is a hack for a test suite to specify the instances that were used to create the test via `create_suite_data.py`. Incommenting line 57 should fix this.

**Comment by brockho** [comment] 2017-06-12 19:23
With 1bb9287, I reverted the test files for the `bbob`, `bbob-biobj`, and `bbob-biobj-ext` suites and also included again the "hack" with the `year: 0000` suite option to create and call the regression tests. All tests ran through on the test branch such that I close this issue now.

**Comment by dtusar** [comment] 2017-06-13 07:08
Some regression test files for 10 and 20 are missing. For `test-suites 10` I get:
```
Traceback (most recent call last):
  File "test_suites.py", line 91, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 52, in regression_test_a_suite
    xfc_dict = literal_eval(open(filename).read())
IOError: [Errno 2] No such file or directory: 'data\\regression_test_10data_for_
suite_bbob-biobj-ext.py'
```

**Comment by brockho** [comment] 2017-06-13 07:24
@dtusar: thanks for the reminder that some of the larger tests are not yet available. However, this is related to #1291, namely the fact that these files will blow up the github repository because they are so large. We should work on the implementation of having them on our svn server instead.

This said, I suggest to close this issue and focus on #1291 to get this done.

**Comment by dtusar** [comment] 2017-06-13 07:36
Okay.

**Closed by dtusar** 2017-06-13 07:36 UTC
Labels: bug, Priority-Critical, Tests & CI
