### ISSUE TITLE
Merge code bases

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#19] opened 2015-08-08 12:21 UTC
```
Merge code bases (if time needed <2h), not only config: is there a problem with 
DataSet becoming a new style class?
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:42

**Comment by nikohansen** [comment] 2016-01-25 18:10
It's not entirely clear which code bases the issue is referencing. The new-style class is at the moment prohibited by the pickle files. See also 20 #45 #46 #56

**Comment by brockho** [comment] 2016-08-19 01:36
Given the last comment of @nikohansen and the already referenced issues are still open, can we close this issue?

**Closed** 2016-08-19 09:09 UTC
Labels: auto-migrated, Code-Postprocessing, question
