### ISSUE TITLE
run-python fails silently

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1698] opened 2018-01-11 10:15 UTC
Calling `python do.py run-python` fails without raising an exception, so it goes unnoticed. 

The problem is that the `example_experiment.py` script requires an additional parameter - the name of the suite, which is missing in `do.py`. The fix for this particular problem is easy - line 346 of `do.py` needs to be changed from
`               ['example_experiment.py'])`
to
`               ['example_experiment.py', 'bbob'])`

However, the more general problem of silent fails also needs to be addressed at some point (not sure whether we already have any open issues on this matter).

BTW, I have tried this on the `development` branch.

**Comment by ShubhGupta2125** [comment] 2018-01-18 04:31
I am a beginner and would like to work on this issue. Can i make the change that you have mentioned above?

**Comment by nikohansen** [comment] 2018-01-18 14:14
You can make the change after you have forked the code (either online or offline). Use the development branch for that. If you try to change the code online, I think at some point the fork will be done automatically, because you are not allowed to change the original code. After that, test the changes via `do.py`. Then you can commit a pull request with the new code to the development branch.

**Comment by ShubhGupta2125** [comment] 2018-01-18 17:30
@nikohansen  please review it.

**Comment by dtusar** [comment] 2018-02-06 15:05
@brockho Can this issue be closed?

**Comment by brockho** [comment] 2018-02-06 17:44
Given what @ttusar wrote above:

"However, the more general problem of silent fails also needs to be addressed at some point (not sure whether we already have any open issues on this matter)."

I guess, the issue is still open.

**Comment by dtusar** [comment] 2018-02-07 12:36
But is this still something that needs to be done for the next release milestone?

**Comment by brockho** [comment] 2018-02-09 11:03
No. I removed the milestone from this issue.

**Comment by olafmersmann** [comment] 2023-03-09 11:22
Closed in anticipation of the 2.6.3 release that replaces `do.py`.

**Closed by olafmersmann** 2023-03-09 11:22 UTC
Labels: bug, wontfix, Code-Experiments
