### ISSUE TITLE
Link "Runtime distribution plots by group (per dimension)" does not work.

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#1013] opened 2016-05-11 12:12 UTC
After post-processing for single objective, there is a link "Runtime distribution plots by group (per dimension)" but it does not work.

**Comment by dtusar** [comment] 2016-05-11 13:30
@NDManh Can you tell me, where do you have this link which does not work. 

I run the post-processing and in the `templateBBOBarticle.html` file I have the link (with the text "Runtime distribution plots by group (per dimension)") to the file `pprldmany-single-functions/pprldmany_gr_02D.html` which does exist in my case.

**Comment by NDManh** [comment] 2016-05-11 13:37
@dtusar : This link is from `templateBBOBarticle.html` and the issue is exactly what you describe above.

**Comment by dtusar** [comment] 2016-05-11 13:39
So I your case the file `pprldmany-single-functions/pprldmany_gr_02D.html` does not exist?

**Comment by NDManh** [comment] 2016-05-11 13:40
Exactly.

**Comment by dtusar** [comment] 2016-05-11 13:45
First, do you have the latest version of the code?

Did you use any particular switch when running the post-processing? 
Do you have the plots for the groups (e.g. `pprldmany_gr_separ_02D.svg`) in the 'pprldmany-single-functions' folder?

**Comment by NDManh** [comment] 2016-05-11 13:54
No, I don't have any plot for the groups, such as `pprldmany_gr_separ_02D.svg` in the folder `pprldmany-single-functions`. In fact, I have used an option '--omit-single' when using post-processing, I don't know whether it is origin of problem?

**Comment by dtusar** [comment] 2016-05-11 13:58
So also the file `templateBBOBarticle.html` was not created (updated) on this run?

**Comment by NDManh** [comment] 2016-05-11 14:09
I've checked, I am using the latest version of branch development.

The file `templateBBOBarticle.html` is created but the link named `Runtime distribution plots by group (per dimension)` inside this file does not work.

**Comment by dtusar** [comment] 2016-05-11 14:20
Can you upload a zip with all the files generated with post-processing (the whole `ppdata` folder).

**Comment by dtusar** [comment] 2016-05-11 14:21
I hope it's not too big.

**Comment by NDManh** [comment] 2016-05-11 14:23
Yes, you could find here.
[ppdata.zip](https://github.com/numbbo/coco/files/259503/ppdata.zip)

**Comment by dtusar** [comment] 2016-05-11 14:29
Now I see that the problem is actually the link in the file `templateBBOBmany.html`. I can reproduce it so that's all I need. Thank you.

**Comment by dtusar** [comment] 2016-05-11 15:30
Fixed with #1016

**Closed by dtusar** 2016-05-11 15:30 UTC

**Comment by NDManh** [comment] 2016-05-13 12:42
@dtusar : This issue is solved for each "Single algorithm data" but not yet for "Comparison data", i.e., we have three following links after click on  "Many algorithm comparison" below "Comparison data":
```
Home

Runtime distribution plots (per dimension)

Runtime distribution plots by group (per dimension)
```
The last link, named `Runtime distribution plots by group (per dimension)`, is not still worked.

**Comment by dtusar** [comment] 2016-05-13 12:49
This was an issue regarding "Comparison data" and it should be solved. The single algorithm data already worked before.

**Comment by NDManh** [comment] 2016-05-13 12:54
Can you re-check it since I have updated the latest version and it does not work. Also, there is something I found for "Single algorithm data" which I do not know it's an issue or not?
<img width="602" alt="capture d ecran 2016-05-13 a 14 44 26" src="https://cloud.githubusercontent.com/assets/16137552/15248454/9a4733d4-191a-11e6-842a-abb3c6fa886b.png">
