### ISSUE TITLE
Timing experiment

### ISSUE THREAD

**Issue by anneauger** [numbbo/coco#529] opened 2016-01-27 13:54 UTC
We used to have a timing experiment to get a rough idea of the time complexity of the algorithm. 

Do we want to have the same type of procedure (i.e. participants run a timing-script and report the timing numbers and describe on which system they were running the timing script ). 

Or do we want to have time stamps in the dat files from which we would extract some relevant numbers on the time complexity of the algorithm.

**Comment by nikohansen** [comment] 2016-01-27 14:01
How about having time stamps in the `.info` files? Specifically, each time a newline is written an out-commented line with a time stamp is added. Would this break the normal read-in procedures?

**Comment by tobiaswagner** [comment] 2016-01-27 14:03
I see some problems with the old procedure of choosing one representative setup (with different dimensions). Depending on design decisions (archive vs. population), algorithms (nondominated sorting, stratification) and indicators used in the algorithm, the number of solutions to be considered can strongly depend on the number of evaluations already passed, the conflict between the objectives, and maybe the structure or even sequence of objectives. I feel it will be hard to define a representative test function and number of evaluations for the timing experiment. If the all times are documented, the picture of the running time of the algorithm will be much clearer.

**Comment by ttusar** [comment] 2016-01-27 14:14
I like the idea of having time stamps in the `.info` files, but I'm afraid it might not work in some cases. For example, what if someone decides to parallelize the experiments and breaks down the suite (decides to use only a subset of functions/dimensions/instances at a time)? Then the time stamps won't tell us much...

**Comment by ttusar** [comment] 2016-01-27 14:30
On a second thought, it think this could work if we provide two time stamps per one line of an `.info` file - a start-stop pair of time stamps. We need this because the program "jumps" from one `.info` file to the other and we cannot be sure that the previous time stamp (the time when the previous experiment ended) marks the beginning of the next experiment.

So if we have a start-stop pair of time stamps per line, we can compute the differences and sum them over all provided info files. Then we'll know the total time of one experiment even if it was broken down to multiple machines/files etc. 

This could be simplified further by outputting the differences (the time needed to complete a line) instead of the two time stamps...

**Comment by dtusar** [comment] 2016-01-27 14:31
@nikohansen Yes, if the timestamp lines are added then the reading of the info file fails. It should be easy to fix though.

**Comment by loshchil** [comment] 2016-01-27 16:03
"if someone decides to parallelize the experiments and breaks down the suite (decides to use only a subset of functions/dimensions/instances at a time)?" 
I separate by functions, dimensions and instances so there might be a potential problem with .info file. I guess it is common for expensive optimization, e.g., was also the case for SMAC runs. Instead, what if the time stamps are saved inside dat files?

**Comment by nikohansen** [comment] 2016-01-27 16:39
I am not a fan of breaking the format of the `.dat` files as being "pure" data files (possibly apart from the first few lines), by adding meta information of, after all, rather minor relevance. On the other hand, if you can convince me that these lines can be easily filtered out (say, 1/2 line of Python code ;-)...

**Comment by loshchil** [comment] 2016-01-27 16:50
two time stamps of the first and last modifications in the end of some/first '%' line a format readable by  datetime.strptime(time, format)

**Comment by nikohansen** [comment] 2016-01-27 16:52
I see, that is, there are only two time stamps in each `.dat` file.

**Comment by loshchil** [comment] 2016-01-27 17:00
one time stamp in comments after each line would be even better, then one could potentially plot performance over time

**Comment by nikohansen** [comment] 2016-01-27 19:05
Then again, if you can convince me that these lines can be easily filtered out (say, 1/2 line of Python code ;-)...

**Comment by nikohansen** [comment] 2016-01-28 13:14
A meta remark on wall clock timings: we are not talking rocket science here. Timing data are unreliable and approximative in all kind of ways. That is, in this case I'd clearly prefer to put effort in finding a simple and transparent way over finding a seemingly "fail-safe" but more complicated way.

**Comment by nikohansen** [comment] 2016-02-25 12:35
This is the current idea:

> In order to get a rough measurement of the time complexity of the algorithm, the wall-clock or CPU time should be measured when running the algorithm on the benchmark suite. The chosen setup should reflect a "realistic average scenario". [#]_ The **time divided by the number of function evaluations is presented separately for each dimension** for which the suite provides benchmark problems. The chosen setup, coding language, compiler and computational architecture for conducting these experiments are described.
> .. [#] 
>  The example experiment code provides the timing output measured over all
>  problems of a single dimension by default. It also can be used to make a record
>  of the same timing experiment with "pure random search", which can serve as 
>  additional base-line data.

This is the modified example experiment output (yet uncommitted code): 
```
[13:31:27] 0 python$ ./example_experiment.py 
COCO INFO: Results will be output to folder exdata/random_search_on_bbob-biobj_budget0002-023
Benchmarking solver '<function random_search' with budget=2*dimension on bbob-biobj suite, Thu Feb 25 13:31:59 2016
Feb25 13h31:59, d=2, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 2.0e-04 seconds/evaluations

Feb25 13h31:59, d=3, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 1.5e-04 seconds/evaluations

Feb25 13h31:59, d=5, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 1.1e-04 seconds/evaluations

Feb25 13h32:00, d=10, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 6.6e-05 seconds/evaluations

Feb25 13h32:01, d=20, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 4.8e-05 seconds/evaluations

Feb25 13h32:02, d=40, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........
    done in 5.2e-05 seconds/evaluations
  bbob-biobj done (3300 of 3300 problems benchmarked), Thu Feb 25 13:32:04 2016 (0h00:05).
```
I checked that for a constant number of evaluations, the timing numbers indeed are increasing with dimension.

**Comment by ttusar** [comment] 2016-03-22 00:48
This is now done for C. The output looks like this:

````
Running the example experiment... (might take time, be patient)
COCO INFO: Results will be output to folder exdata/RS_on_bbob-biobj-022

COCO INFO: 22.03.16 01:35:46, d=2, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done
COCO INFO: 22.03.16 01:35:47, d=3, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done
COCO INFO: 22.03.16 01:35:48, d=5, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done
COCO INFO: 22.03.16 01:35:50, d=10, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done
COCO INFO: 22.03.16 01:35:51, d=20, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done
COCO INFO: 22.03.16 01:35:53, d=40, running: f01..........f02..........f03..........f04..........f05..........f06..........f07..........f08..........f09..........f10..........f11..........f12..........f13..........f14..........f15..........f16..........f17..........f18..........f19..........f20..........f21..........f22..........f23..........f24..........f25..........f26..........f27..........f28..........f29..........f30..........f31..........f32..........f33..........f34..........f35..........f36..........f37..........f38..........f39..........f40..........f41..........f42..........f43..........f44..........f45..........f46..........f47..........f48..........f49..........f50..........f51..........f52..........f53..........f54..........f55..........done

d=2 done in 4.55e-04 seconds/evaluation
d=3 done in 3.03e-04 seconds/evaluation
d=5 done in 3.64e-04 seconds/evaluation
d=10 done in 9.09e-05 seconds/evaluation
d=20 done in 9.09e-05 seconds/evaluation
d=40 done in 1.14e-04 seconds/evaluation
Total elapsed time: 0h00m12s
Done!
````

All timing output is aggregated at the end because I couldn't fit it nicely within the info output produced by each call to `coco_suite_get_next_problem()`. @brockho, you will probably encounter the same issue in Matlab.

**Comment by ttusar** [comment] 2016-03-22 13:05
Done for Java as well.

**Comment by nikohansen** [comment] 2016-03-22 14:07
> All timing output is aggregated at the end

which might be even better than the original version, at least if the experiment runs through.

**Comment by brockho** [comment] 2016-03-22 23:27
The Matlab code now also gives the required timing experiment output (merged into the `doc` branch for the moment).

Regarding the note of @nikohansen, I can confirm that for a fixed number of function evaluations, the time per function evaluation for RANDOMSEARCH increases with dimension, e.g. for 1,000 function evaluations:
```
   COCO TIMING: dimension 2 finished in 6.344727e-005 seconds/evaluation
   COCO TIMING: dimension 3 finished in 7.119862e-005 seconds/evaluation
   COCO TIMING: dimension 5 finished in 6.870939e-005 seconds/evaluation
   COCO TIMING: dimension 10 finished in 7.136226e-005 seconds/evaluation
   COCO TIMING: dimension 20 finished in 7.401332e-005 seconds/evaluation
   COCO TIMING: dimension 40 finished in 8.960876e-005 seconds/evaluation
```
and for 10,000 function evaluations:
```
   COCO TIMING: dimension 2 finished in 4.924263e-005 seconds/evaluation
   COCO TIMING: dimension 3 finished in 4.908335e-005 seconds/evaluation
   COCO TIMING: dimension 5 finished in 5.086255e-005 seconds/evaluation
   COCO TIMING: dimension 10 finished in 5.322341e-005 seconds/evaluation
   COCO TIMING: dimension 20 finished in 5.732110e-005 seconds/evaluation
   COCO TIMING: dimension 40 finished in 6.793170e-005 seconds/evaluation
```

**Comment by brockho** [comment] 2016-03-22 23:28
@nikohansen: Is the python example experiment now updated and prints the timing information as above? In other words, can we close this issue?

**Comment by nikohansen** [comment] 2016-03-23 12:20
Now looks like this
```
Mar23 13h21:20, d=20, running: f01..........(10)  f02..........(10)  f03..........(10)  f04..........(10)  f05..........(10)  f06..........(10)  f07..........(10)  f08..........(10)  f09..........(10)  f10..........(10)  f11..........(10)  f12..........(10)  f13..........(10)  f14..........(10)  f15..........(10)  f16..........(10)  f17..........(10)  f18..........(10)  f19..........(10)  f20..........(10)  f21..........(10)  f22..........(10)  f23..........(10)  f24..........(10)  f25..........(10)  f26..........(10)  f27..........(10)  f28..........(10)  f29..........(10)  f30..........(10)  f31..........(10)  f32..........(10)  f33..........(10)  f34..........(10)  f35..........(10)  f36..........(10)  f37..........(10)  f38..........(10)  f39..........(10)  f40..........(10)  f41..........(10)  f42..........(10)  f43..........(10)  f44..........(10)  f45..........(10)  f46..........(10)  f47..........(10)  f48..........(10)  f49..........(10)  f50..........(10)  f51..........(10)  f52..........(10)  f53..........(10)  f54..........(10)  f55..........(10)  
    done in 1.3e-05 seconds/evaluation

Mar23 13h21:22, d=40, running: f01..........(10)  f02..........(10)  f03..........(10)  f04..........(10)  f05..........(10)  f06..........(10)  f07..........(10)  f08..........(10)  f09..........(10)  f10..........(10)  f11..........(10)  f12..........(10)  f13..........(10)  f14..........(10)  f15..........(10)  f16..........(10)  f17..........(10)  f18..........(10)  f19..........(10)  f20..........(10)  f21..........(10)  f22..........(10)  f23..........(10)  f24..........(10)  f25..........(10)  f26..........(10)  f27..........(10)  f28..........(10)  f29..........(10)  f30..........(10)  f31..........(10)  f32..........(10)  f33..........(10)  f34..........(10)  f35..........(10)  f36..........(10)  f37..........(10)  f38..........(10)  f39..........(10)  f40..........(10)  f41..........(10)  f42..........(10)  f43..........(10)  f44..........(10)  f45..........(10)  f46..........(10)  f47..........(10)  f48..........(10)  f49..........(10)  f50..........(10)  f51..........(10)  f52..........(10)  f53..........(10)  f54..........(10)  f55..........(10) 
    done in 2.1e-05 seconds/evaluation
  dimension seconds/evaluations
  -----------------------------
      2      2.6e-05 
      3      2.2e-05 
      5      1.7e-05 
     10      1.2e-05 
     20      1.3e-05 
     40      2.1e-05 
  -----------------------------
  bbob-biobj done (3300 of 3300 problems benchmarked), Wed Mar 23 13:21:32 2016 (0h00:15 total elapsed time).
```
in Python (not committed yet).

**Closed by nikohansen** 2016-03-23 12:20 UTC
Labels: Priority-High
