### ISSUE TITLE
Remove all links to gforge.inria.fr

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#2057] opened 2021-12-07 16:08 UTC
In all `numbbo` repositories, not just `coco`

**Comment by brockho** [comment] 2023-10-26 11:00
* [x] numbbo/coco
* [ ] numbbo/coco-doc
* [ ] numbbo/regression-tests
* [ ] numbbo/ppdata-archive
* [x] numbbo/coco-next 
* [ ] numbbo/workshops
* [ ] numbbo/data-archive
* [ ] numbbo/numbbo.github.io
* [ ] numbbo/bbob-biobj
* [ ] numbbo/cocopp-playground

**Comment by brockho** [comment] 2024-01-15 09:41
Looks like we forgot to close this issue during our COCO sprint in November.

**Closed by brockho** 2024-01-15 09:41 UTC
