### ISSUE TITLE
Postprocessing incomplete data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1411] opened 2017-06-13 12:27 UTC
It will be nice if the postprocessing can handle incomplete data sets (e.g. from currently running experiments). At the moment, it crashes in the case when the `.info` file is not written properly.

**Comment by nikohansen** [comment] 2017-07-09 14:26
Given that experiments can take hours or days, this is a rather indispensable feature and should come back ASAP, hence critical priority.

**Comment by nikohansen** [comment] 2017-07-11 13:19
While reading in, data which have not been finalised (according to the `.info` file) should not be read in, but a warning should be issued instead.

**Comment by dtusar** [comment] 2017-09-08 12:18
This should be fixed now.

**Comment by islandblue** [comment] 2017-10-27 15:35
At this point, I would welcome...

1. advice on which data to use for tests (preferably as full-featured as possible)
2. improper .info files, if anyone has any lying around

...both of which would save me some work before I can test the new code.

**Comment by nikohansen** [comment] 2017-10-28 11:02
I would use `example_experiment_for_beginners.py` in `build/python` (in combination with `Crtl-C`) as test data generator. This is probably quicker than trying to find broken index files on the computer.

**Comment by brockho** [comment] 2017-10-28 20:51
Just a clarification: Run the experiment with a high enough `BUDGET_MULTIPLIER`, e.g. `1e4` or so. This will increase the chance that the experiment is actually producing a currently unsupported state of its data when pressing `Ctrl-C`. Running the default `example_experiment_for_beginners` might have a too quick experiment per function/dimension/instance such that hitting the `Ctrl-C` at "the right time" might be too unlikely.

**Comment by brockho** [comment] 2018-01-02 15:19
This issue seems to be solved. Today, with the latest `development` branch, I run a very long experiment on `bbob` and, while it ran, called the postprocessing. I made sure to call the postprocessing in between a run and this worked, displaying only the two functions that were finished at the time the postprocessing was called.

**Comment by islandblue** [comment] 2018-01-02 15:29
I've spent the better part of the afternoon trying to reproduce the problem, ran around 100 interrupted experiments, but the only occurence where the old post-processing code fails remains the one I've been working on since the beginning. This is very inconclusive. I would have preferred to demonstrate more cases where the old code fails and the new code works. I'm trying with an even larger budget now. If that too fails to produce a problem case, it's either that running and interrupting the example experiment is not a good way to produce problem cases or that problem cases are very rare anyway. I will post again with the results today.

**Comment by islandblue** [comment] 2018-01-02 16:36
I'm attaching a total of three incomplete experiments that fail with commit `d7a4da6` and run through with commit `cab8e34`. Took me 200+ tries to get the three problem cases, so please let me know if you want more/different proof. Otherwise I think the issue can be closed for now. We can always reopen if any incomplete experiment fails to post-process in the future.

[incomplete_experiments.zip](https://github.com/numbbo/coco/files/1598060/incomplete_experiments.zip)

**Closed** 2018-01-04 12:34 UTC
Labels: Code-Postprocessing, Priority-Critical, Type-Defect, Usability
