### ISSUE TITLE
Fixed-target ECDF plots broken for bbob-biobj

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1670] opened 2017-11-23 22:31 UTC
When postprocessing a recently produced data set (NSGA-II from [platypus](https://github.com/Project-Platypus/Platypus) with a budget of only 10n function evaluations, see [exdata-platypus-NSGA-II-m100p100-budget10D.zip](https://github.com/numbbo/coco/files/1500255/exdata-platypus-NSGA-II-m100p100-budget10D.zip)), and comparing it with the NSGA-II from the data-archive, I got very strange fixed target ECDFs such as 

![pprldistr_05d_all](https://user-images.githubusercontent.com/13706996/33189707-b9675cb4-d0a5-11e7-91e8-f92e66c67945.png)

[aggregation over all functions in 5-D]

Strange:
* the graph for one algorithm (according to the caption, the platypus one) going up that directly to 1.0 right at 20n function evaluations
* the markers for the other algorithm

**Comment by nikohansen** [comment] 2017-11-29 16:25
The markers seems to suffer from some sort of index shift by one: e.g., the first marker is placed on its own y-value and on the y-value of the second marker...

**Comment by brockho** [comment] 2017-12-21 15:11
When we looked again at the plot (and only the plot), we realized that for the platypus algorithm no target was actually hit: the line on the left with the circled markers is very likely the max-budget line and not a data line.

Maybe, the wrong markers come from the fact that one data for one algorithm is empty here.

**Comment by islandblue** [comment] 2018-01-17 14:25
I failed to reproduce this plot. I get the following:

![pprldistr_05d_noiselessall](https://user-images.githubusercontent.com/27438398/35047255-a2f0134e-fb99-11e7-8767-08f6cf9c7179.png)

I got this by running `python -m cocopp exdata NSGA-II` where exdata is the contents of the archive @brockho linked and `NSGA-II` resolves to `NSGA-II-MATLAB_Auger_bbob-biobj`. cocopp is the latest commit to the development branch ([`d970bffe`](https://github.com/numbbo/coco/tree/d970bffe06a953c585f9424a7a6121cbc1520467)) and I used Python 2.7.

@brockho, if you used a different method, I'd like to retrace your steps.

**Comment by islandblue** [comment] 2018-01-18 13:38
It occurred to me to try `python -m cocopp NSGA-II exdata` just in case order matters. Same result though.

**Comment by islandblue** [comment] 2018-01-18 15:33
Post-processed the same data 20 times, in case the bug is RNG-related. Still can't get a buggy graph.

**Comment by brockho** [comment] 2018-01-18 17:14
Very strange. I postprocessed again two algorithms today with (what I think is) the current development branch (after cleaning-up and re-installing the `cocopp` module) and I still get the same plots.

Can somebody else than @islandblue please have a look whether this appears or not? Simply take any two algorithms, postprocess them and look at the figures you see under the last link in the html output.

**Comment by ttusar** [comment] 2018-01-19 09:14
I downloaded the NSGA-II data from:
- [exdata-platypus-NSGA-II-m100p100-budget10D.zip](https://github.com/numbbo/coco/files/1500255/exdata-platypus-NSGA-II-m100p100-budget10D.zip) (platypus)
- [NSGA-II-MATLAB_Auger_bbob-biobj.tgz](http://coco.gforge.inria.fr/data-archive/bbob-biobj/2016/NSGA-II-MATLAB_Auger_bbob-biobj.tgz) (matlab). 

With `cocopp-2.0.760` (calling `python -m cocopp platypus matlab`), the result is as follows:

![slika](https://user-images.githubusercontent.com/13745935/35143244-4a7fc2d6-fd01-11e7-8c4e-17ada381cfb5.png)

**Comment by islandblue** [comment] 2018-01-19 09:43
Thank you @ttusar.

The code that generates the marker locations and everything immediately before and after that is called twice, once for each experiment data. Far as I can see, all relevant variables are in local scope. Presently I don't see how anything about the first experiment data could affect the other's plot.

I'll try to put in some extra debug lines and ask one you to run it, see if it gives us a clue.

**Comment by brockho** [comment] 2018-01-19 10:58
No, the type of algorithm data seems to have no effect. I tried with older public `bbob` data sets such as BFGS and BIPOP-CMA and I saw the same thing.

**Comment by islandblue** [comment] 2018-01-22 14:38
@brockho's original graph is buggy, but I cannot tell whether mine is correct either. I ran `BFGS_ros_noiseless` vs. `BIPOP-CMA-ES_hansen_noiseless` as per @brockho's last experiment and got the following graph.

![refgraph](https://user-images.githubusercontent.com/27438398/35223694-9ff0df92-ff82-11e7-8b4b-d2509c280a79.png)

So, assuming this is a proper graph, I made the following observations.

- We would normally expect two lines of each color, whereas with platypus we have only one. I get the feeling this is the intended behavior since platypus data has nothing to plot. Correct? Then the lines that are visible are plotted with NSGA-II data.
- There are extra markers in @brockho's graph. These markers have the same shape as the markers on the line, so there's a good chance they are placed by the same call that plotted the corresponding line. That is, the call that has NSGA-II datasets as its argument, not the platypus one. Therefore I wouldn't expect it to have gone the way @dtusar suggested.

**Comment by islandblue** [comment] 2018-01-22 14:41
Could you run the code in [`islandblue-issue1670`](https://github.com/numbbo/coco/tree/islandblue-issue1670) branch with redirected output and share the file? I did it and get debug logs that match the graph I'm getting. The difference in yours should lead us to the problem.

**Comment by nikohansen** [comment] 2018-01-23 13:14
> I ran BFGS_ros_noiseless vs. BIPOP-CMA-ES_hansen_noiseless as per @brockho's last experiment and got the following graph.
> So, assuming this is a proper graph

Mostly proper, one thing is strange though: the second black vertical line seem to have the wrong symbols. In the original graph both vertical lines have the symbols I would expect.

**Comment by islandblue** [comment] 2018-01-25 15:27
Oddly enough, removing the update_from() calls did not help with the misplaced extra markers in my case.

**Comment by islandblue** [comment] 2018-01-31 11:35
The problem has been identified and the fix is ready, pending test. The initial tests failed due to unrelated reasons, which were identified in issue #1703 and being addressed in pull request #1704. When #1704 is merged into `development` branch, `islandblue-issue1670` branch will be re-based on `development` and the pull request will be created.

**Closed** 2018-02-13 14:10 UTC
Labels: Code-Postprocessing, bug
