### ISSUE TITLE
[Bug report] Postprocessing incompatible with python 3.10

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2152] opened 2023-01-13 09:04 UTC
**Describe the bug**
It seems that the COCO postprocessing is not compatible (yet) with python 3.10 (and most likely with python 3.11 as well):

```
Post-processing (1)
  loading data...
C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cocopp\pproc.py:1075: UserWarning:   instance numbers not among the ones specified in 2009, 2010, 2012, 2013, and 2015-2018
  warnings.warn('  instance numbers not among the ones specified in 2009, 2010, 2012, 2013, and 2015-2018')
  Will generate output data in folder ppdata\random_search_of_cocoex.solvers_2D_on_bbob-003
    this might take several minutes.
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: c:\users\[...localpath...]\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\cocopp\refalgs/best2009-bbob.tar.gz
  done (Tue Jan 10 20:41:53 2023).
Traceback (most recent call last):
  File "C:\Users\[...localpath...]\code-experiments\build\python\example_experiment2.py", line 197, in <module>
    cocopp.main(observer.result_folder)  # re-run folders look like "...-001" etc
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cocopp\rungeneric.py", line 408, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cocopp\rungeneric1.py", line 154, in main
    ppfigdim.main(dsList, values_of_interest, algoutputdir)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cocopp\ppfigdim.py", line 595, in main
    ppfig.save_figure(filename, dsList[0].algId)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cocopp\ppfig.py", line 97, in save_figure
    plt.savefig(filename + '.' + format,
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\pyplot.py", line 954, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 2285, in print_figure
    with cbook._setattr_cm(self, manager=None), \
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 2188, in _switch_canvas_and_return_print_method
    canvas_class = get_registered_canvas_class(fmt)
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 146, in get_registered_canvas_class
    backend_class = importlib.import_module(backend_class).FigureCanvas
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\backend_pdf.py", line 43, in <module>
    from . import _backend_pdf_ps
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\_backend_pdf_ps.py", line 8, in <module>
    from fontTools import subset
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontTools\subset\__init__.py", line 17, in <module>
    from fontTools.varLib import varStore  # for subset_varidxes
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontTools\varLib\__init__.py", line 35, in <module>
    from fontTools.varLib.iup import iup_delta_optimize
  File "C:\Users\[...localpath...]\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontTools\varLib\iup.py", line 17, in <module>
    if cython.compiled:
AttributeError: module 'cython' has no attribute 'compiled'
```

Many thanks to Zeidan Braik for reporting this issue.

**Comment by ttusar** [comment] 2023-01-13 09:09
FYI, I witnessed postprocessing working just fine on Python 3.11.

**Comment by nikohansen** [comment] 2023-01-18 15:00
Just remarking that it happens in `savefig` and then `fontTools` and `cython` come up in the message.

**Comment by nikohansen** [comment] 2023-01-18 16:23
It may well be that
```
pip install cython
```
solves this issue.

**Comment by olafmersmann** [comment] 2023-01-18 20:53
Just tried running the post-processing using Python 3.10 under Linux and could not reproduce the error. Can Zeidan Braik provide a list of all installed packages with their corresponding version (i.e. the output of `pip list`)?

**Comment by brockho** [comment] 2023-01-18 22:00
> It may well be that
> 
> ```
> pip install cython
> ```
> 
> solves this issue.

Indeed, this solved the issue.

**Comment by olafmersmann** [comment] 2023-01-18 22:34
Can we close the issue or should we investigate further and possibly add `cython` as an explicit dependency to `cocopp`?

**Comment by nikohansen** [comment] 2023-01-19 00:42
To me it looks like a bug in `fontTools` is generating this "dependency", so this would be a little strange...

**Closed** 2023-01-19 08:23 UTC
Labels: bug, Code-Postprocessing
