### ISSUE TITLE
Error when scaling figures (post-processing)

### ISSUE THREAD

**Issue by melovv** [numbbo/coco#1077] opened 2016-06-15 15:50 UTC
Dear all,

I'm running the following command with the results of 18 algorithms (results from GECCO'15 plus my results):

python coco-master/code-postprocessing/bbob_pproc/rungenericmany.py --settings grayscale --expensive  LIST_OF_ALGS

The error is:
...
Generating comparison tables...
None
  done (Wed Jun 15 11:55:46 2016).
Scaling figures...
Traceback (most recent call last):
  File "coco-master/code-postprocessing/bbob_pproc/rungenericmany.py", line 32, in <module>
    res = cocopp.rungenericmany.main(sys.argv[1:])
  File "/home/professor/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungenericmany.py", line 450, in main
    genericsettings.verbose)
  File "/home/professor/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/compall/ppfigs.py", line 450, in main
    tmp = plt.plot(dimert[idim:idim+2], ert[idim:idim+2], **styles[i]) #label=alg, )
IndexError: list index out of range

Also, in the files named "pprldmany_XXXD_noiselessall.pdf":
1 - the curves and points near to value 0.0 are getting out of the lower limits (below 0.0);
2 - there is a series of "15, 15, ..." that I'd like to remove;
3 - there are dots over the legends  that I'd like to remove.

Dimo Brockhoff wrote me:

"For the moment, you can fix the bug yourself, by replacing the line

   fix_styles(len(sortedAlgs))  #

in the compall/ppfigs.py file with

   fix_styles(len(sortedAlgs), styles)  #

That solved the problem for me (in my file, the bug was in line 413). "

However, it did not solve the above mentioned issues. Please see the attached file.

Sorry for creating this issue if this has already been commented in another one.

Best regards,

Vinícius.

[pprldmany_20D_noiselessall.pdf](https://github.com/numbbo/coco/files/316513/pprldmany_20D_noiselessall.pdf)

**Comment by brockho** [comment] 2016-06-15 20:38
Dear Vinícius,

Just to be sure, am I right if I interpret the following: (i) the suggested addition of the ``styles`` parameter did fix the bug, i.e., the scaling plots are generated but (ii) the three issues with the ``pprldmany_XXXD_noiselessall.pdf`` files (the above 1-2-3) remain?

If this is the case, please find below my comments on your issues 1-2-3, if this is not the case (and the bug is still present, could you please let us know a bit more details (which machine, operating system, python version, ... you use)?

Answer to 1)
What is displayed on the x-axis of the ECDF plot you attached is the number of function evaluations divided by dimension (which is 20 in your case). That means that in your plot, the first function evaluation is supposed to appear at a value of 1/20, which is definitely to the left of the 0 (note that the x-axis is displayed in log-scale). The displayed values are therefore not "out of the lower limits" but show the actual numbers. For this reason, you should observe that the graphs start the more to the left, the larger the dimension.

Answer to 2)
The 15 indicate the number of instances displayed for each algorithm and is therefore an important information, but I can understand that for many algorithms, this line is a bit too much. If you want to get rid of this line, you should delete the lines 803 till 811 in the ``compall/pprldmany.py`` file:
```
    # add number of instances 
    text += '\n'
    for alg in algorithms_with_data:
        if dictAlgperFunc[alg]:
            text += '%d, ' % len(dictAlgperFunc[alg][0].instancenumbers)
        else:
            text += '0, '
    text = text.rstrip(', ')
    text += ' instances'
```

Answer to 3)
Why do you want to get rid of the dots? They are actually part of the ECDF graph and display the last point of the (bootstrapped) ECDF that is still within the plot. I would therefore strongly suggest to keep those points.

**Comment by melovv** [comment] 2016-06-22 19:05
Dear Dimo.

Thank you very much for answering. 

The scaling problem was fixed, yes, but I was wondering it would also correct what I called "out of limits" plot. I comment your answers below.


Regarding the machine:

Linux Ubuntu 14.04 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2

numpy.__version__
'1.8.2'

matplotlib.__version__
'1.3.1'

Yes, it is outdated. I’ll try running the code on an updated machine to see if it works.


Comment to answer 1)
I understand what you say and I’ll use the plots as they are. My argument was that the plot limits are from 0 to 3 (actually more because of the labels on the right), thus, log10(1/20) = -1.3 is out of the limits. That's why the curves and points are over the labels. Also, you may notice that the curves start close to zero, while the points start far back. The first point is for Sif and is barely visible. Probably, there are other points missing. Maybe it is because of the outdated version of my system?


Comment to answer 2)
Thanks for the patch. It worked. Just for reference, I had to delete the build and dist folders in coco/post-processing and reinstall the package: python do.py install-postprocessing

As a suggestion, would it be better to change the upper ylim to 1.1 or 1.2 to have space to write that text?


Comment to answer 3)
I understand the importance of those dots. However, they are barely visible and the plot is in grayscale, so, it is hard to distinguish the many algorithms from the dots. Nevertheless, I’ll keep them.


Best regards,

Vinícius.

**Comment by brockho** [comment] 2016-08-07 19:16
I'll take care of the remaining things with #68.

**Comment by brockho** [comment] 2016-08-10 16:48
I have the feeling that the issue can be closed by now (and easily be reopened if truly needed), even if #68 is not solved yet:

ad 1)
> Also, you may notice that the curves start close to zero, while the points start far back.
I cannot reproduce this with the current code and the grayscale setting. @melovv: would you be so kind and check again and let us know if the problem persists?

ad 2)
> As a suggestion, would it be better to change the upper ylim to 1.1 or 1.2 to have space to write that text?
The text is now definitely shorter than before for many algorithms and should most of the time fit. Making the ylim larger than 1 will (i) look strange for a plot that is naturally bounded above by the value 1 and therefore will (ii) add unnecessary white space on the right. For those reasons, I would like to stay with the current version.

**Closed by brockho** 2016-08-10 16:48 UTC
