### ISSUE TITLE
Different font in pdf files.

### ISSUE THREAD

**Issue by mariosky** [numbbo/coco#1335] opened 2017-04-06 07:34 UTC
![screen shot 2017-04-06 at 12 25 25 am](https://cloud.githubusercontent.com/assets/1169158/24742627/ea38fc1e-1a5f-11e7-8074-0b3cbca76246.png)

When graphs are generated by the post-processing script, pdfs have a wider font in titles and axes. I am using Mac OS Sierra. I also tried creating the graphs in Linux and with the developer branch without success. Is anyone having this issue?

**Comment by brockho** [comment] 2017-04-06 12:05
Hi. Thanks for reporting this issue. I think I have seen this already, but at the moment, I cannot reproduce the wrong figures in my setting (Windows 7 with Python 2.7.11 via Anaconda 4.0.0 and Adobe Acrobat Reader DC). Would you be so kind and upload the pdf directly? Just to check that this is not a "bug" with your pdf viewer. Thanks in advance.

**Comment by mariosky** [comment] 2017-04-06 13:00
[ppfigdim_f003.pdf](https://github.com/numbbo/coco/files/902572/ppfigdim_f003.pdf)
Here it is.

**Comment by brockho** [comment] 2017-04-06 13:30
When looking at your pdf, I have the same problem. It seems, indeed, as if a font is missing on your side. However, I am not aware that we use any Windows-specific font since COCO shall run on all kinds of machines due to the system-independence of python.

As you suggested, the problem might come from matplotlib. I, myself, have matplotlib 1.5.1, the latest stable release is 2.0.0. Can you tell us which version you have (type ``matplotlib.__version__`` after ``import matplotlib`` in an (i)python shell)?

**Comment by mariosky** [comment] 2017-04-06 14:30
I have tried with versions 2.0.0 and 1.4.7. I will try it in Windows to see if it is specific to Mac.

**Comment by mariosky** [comment] 2017-04-07 00:04
Hi, I did not remember your version so I did a pip install matplotlib==1.4.3 and it worked fine.
I will try to generate some LaTeX tables I was having problems with and report if this also corrected that. @brockho thank you for your help.

**Comment by mariosky** [comment] 2017-04-07 00:17
When I run the scripts with matplotlib version 2.0.0 a Warning is printed:
ECDF graphs per function...
/Users/mario/.local/lib/python2.7/site-packages/cocopp-2.0.1-py2.7.egg/cocopp/ppfig.py:487: RuntimeWarning: invalid value encountered in log10
  min([min(xdata), ax_limits[0], ax_limits[1]]) + 0.5)  # np.log10(xdata[-1]) - np.log10(xdata[0])

**Comment by brockho** [comment] 2017-04-18 13:43
We mention the issue now in the known issues of the overall README.md such that we can close it here.

**Comment by nikohansen** [comment] 2017-04-20 11:02
Sorry, we currently don't see any solution other than playing with different `matplotlib` versions. This is clearly suboptimal and I would still like to keep this issue open to incentive looking for a better solution.

**Comment by nikohansen** [comment] 2017-05-24 19:12
It seems to be a `matplotlib` issue and addressed in v2.0.1, see [https://github.com/matplotlib/matplotlib/issues/7937].

**Closed by nikohansen** 2017-05-24 19:12 UTC
Labels: Code-Postprocessing, Priority-High
