### ISSUE TITLE
Cocopp Bbob Linestyle Error

### ISSUE THREAD

**Issue by Kem7272** [numbbo/coco#2001] opened 2020-12-12 14:26 UTC
Hello, 

I am a beginner and I have an issue to compare more than one algorithm by specifying several data result folders generated by different algorithms. 

For example, I would like to compare the 'RS_on_bbob-001' and 'RS_on_bbob-002'. 
This is what I typed in command prompt: 
`python -m cocopp exdata\RS_on_bbob-001 exdata\RS_on_bbob-002`

And this is what I get: 
```
(base) C:\Users\Kem\Desktop\matlab>python -m cocopp exdata\RS_on_bbob-001 exdata\RS_on_bbob-002
Post-processing (2+)
  Using:
    exdata\RS_on_bbob-001
    exdata\RS_on_bbob-002

Post-processing (2+)
  loading data...
  Data consistent according to consistency_check() in pproc.DataSet
  using: exdata\RS_on_bbob-001
  Data consistent according to consistency_check() in pproc.DataSet
  using: exdata\RS_on_bbob-002
  Will generate output data in folder ppdata\RS_on_RS_on
    this might take several minutes.
ECDF runlength ratio graphs...
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:147: RuntimeWarning: invalid value encountered in true_divide
  x.append((tmp1/tmp0).flatten())  # inf/inf results in nan
C:\Users\Kem\anaconda3\lib\site-packages\cocopp\comp2\pprldistr2.py:80: UserWarning: FixedFormatter should only be used together with FixedLocator
  axisHandle.set_xticklabels([str(int(numpy.log10(xx))) for xx in x])
  done (Sat Dec 12 21:51:58 2020).
ECDF runlength graphs...
Traceback (most recent call last):
  File "C:\Users\Kem\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Kem\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\rungeneric.py", line 390, in main
    dsld = rungenericmany.main(args, outputdir)
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\rungenericmany.py", line 290, in main
    many_algorithms_output, 'all')
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\pprldistr.py", line 598, in comp
    **rldStyles[j % len(rldStyles)])
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\pprldistr.py", line 508, in plotRLDistr
    res = plotECDF(x, nn, **kwargs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\pprldistr.py", line 391, in plotECDF
    drawstyle='steps', **plotArgs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\cocopp\ppfig.py", line 574, in plotUnifLogXMarkers
    res2 = plt.plot(x2, y2, **marker_args)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2842, in plot
    **({"data": data} if data is not None else {}), **kwargs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1742, in plot
    kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\Kem\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 1751, in normalize_kwargs
    raise TypeError(f"Got both {canonical_to_seen[canonical]!r} and "
TypeError: Got both 'ls' and 'linestyle', which are aliases of one another
```

I am using python 3.7.9, matplotlib 3.3.2, scipy 1.5.2, numpy 1.9.2, six 1.15.1 and MatLab R2019a. 
It works fine with single algorithm data but not comparison of multiple algorithms. 
Did anyone face this issue before?
Did I misunderstand [point number 6](https://github.com/numbbo/coco/blob/master/README.md#Getting-Started-pp)?

**Comment by brockho** [comment] 2020-12-12 19:54
Many thanks for your report. I tried to reproduce the error with my settings but neither on the current master branch nor on the development branch I see the error (tested though only with python-prepared data sets). Most likely, incompatible module versions make the difference.

I originally had the following: python 3.7.3, matplotlib 3.1.2, scipy 1.2.1, numpy 1.16.2, six 1.15.0

After upgrading, I now have matplotlib 3.3.3, scipy 1.5.4, numpy 1.19.4, six 1.15.0 and still cannot reproduce the error.

Could you please let us know your COCO version?
```python
>>> import cocopp
>>> cocopp.__version__
'2.3.3.111'
```

**Comment by Kem7272** [comment] 2020-12-13 03:17
Hi, @brockho . Thanks for your reply. 
My COCO version is '2.3.3.18'.

**Comment by nikohansen** [comment] 2020-12-13 23:20
FTR, it's a known error which came from newer versions of `matplotlib` which then had been fixed in newer versions of `cocopp`.

Version `2.3.3.18` is the one which comes with `pip install cocopp`. We will update this ASAP.

The current workaround would be to `git clone` the repository and `python do.py install-postprocessing --user` in the repository root.

**Comment by nikohansen** [comment] 2020-12-13 23:40
My current master branch is of version `'2.3.3.18.65'`. I am not sure this is how it is supposed to be?

**Comment by Kem7272** [comment] 2020-12-14 02:41
Hi @nikohansen , thanks for your reply. 
It works for me after `git clone` and `python do.py install-postprocessing --user` as suggested. 

> FTR, it's a known error which came from newer versions of `matplotlib` which then had been fixed in newer versions of `cocopp`.
> 
> Version `2.3.3.18` is the one which comes with `pip install cocopp`. We will update this ASAP.
> 
> The current workaround would be to `git clone` the repository and `python do.py install-postprocessing --user` in the repository root.

However, I check my cocopp version by
```
import cocopp
cocopp.__version__
```
It shows to be version '0.0.0'. 
I am not sure this is how it is supposed to be?

**Comment by Kem7272** [comment] 2020-12-14 04:28
I have try again `python do.py install-postprocessing --user`. 
It shows to be version '2.3.3.84'.

**Comment by nikohansen** [comment] 2020-12-14 14:59
The graphs look good to me, why should they go from 0 to 8?

**Comment by Kem7272** [comment] 2020-12-15 02:03
Just wonder why the graphs from other literatures, the x-axes are shown from 0 to 8. 
For examples, 
![image](https://user-images.githubusercontent.com/75886769/102158334-3510cf80-3ebc-11eb-95c4-266b69ba8872.png)

Anyway, it is great if this is how it supposed to be. 
> I have try again `python do.py install-postprocessing --user`.
> It shows to be version '2.3.3.84'.
> 
> For ECDFs graph, the labels of the x-axis shows only 0 to 6 instead of 0 to 8.
> Is it supposed to be like that?
> For examples,
> [pprldmany_02D_hcond.pdf](https://github.com/numbbo/coco/files/5687835/pprldmany_02D_hcond.pdf)
> [pprldmany_05D_hcond.pdf](https://github.com/numbbo/coco/files/5687838/pprldmany_05D_hcond.pdf)

Thanks @nikohansen and @brockho for your help. Very much appreciate.

**Comment by brockho** [comment] 2020-12-15 08:01
Now we see what you mean. In previous plots, there was indeed an annotation of "8" although no data was shown after `10^7` times dimension function evaluations. The lines you see in the old plots after the "7" are just indicating which algorithm name belongs to which ECDF line (and is no actual data). This caused some confusion for users in the past which is why we removed this annotation. The actually displayed data was and still is shown until `10^7` times dimension.

**Comment by Kem7272** [comment] 2020-12-15 08:46
@brockho Thanks for your explanation. Appreciate.

**Closed** 2020-12-15 09:00 UTC
Labels: bug

**Comment by nikohansen** [comment] 2020-12-15 14:21
Now `cocopp` version 2.4 is [on PyPI](https://pypi.org/project/cocopp).

**Comment by Kem7272** [comment] 2020-12-15 15:05
> Now `cocopp` version 2.4 is [on PyPI](https://pypi.org/project/cocopp).

Thanks for the update.
